H_course = [
    'Mi estas besto.',
    'Mi loĝas en Afriko kaj Hindio.',
    'Mi havas longan nazon kaj grandajn orelojn.',
    'Miaj okuloj estas malgrandaj.',
    'Kiu mi estas?',
    'Mi loĝas en Ĉinio.',
    'Mi loĝas ankaŭ en zoologia ĝardeno.',
    'Mi estas populara en zoologia ĝardeno.',
    'Mi ŝatas etbambuon.',
    'Mi estas blanka kaj nigra.',
    'Mi povas flugi tre rapide.',
    'Per flugiloj mi povas flugi.',
    'Sed mi ne estas birdo!',
    'Mi povas flugi al Novjorko, Moskvo, Varsovio, Parizo, Londono...',
    'Mi povas kuri rapide.',
    'Miaj dentoj estas akraj.',
    'Mi estas forta.',
    'Mi estas reĝo de bestoj.',
    'Mi havas 4 piedojn.',
    'Sed mi ne estas besto.',
    'Mi trinkas benzinon.',
    'Mi estas tre granda.',
    'Mi estas blanka.',
    'Mi estas globa.',
    'Mia patrino estas kokino.',
    'Mi estas en la mezo de Linio Jamanote.',
    'Mi povas kuri tre rapide.',
    'Mi povas iri pli rapide ol jeto, ol spacoŝipo.',
    'Mi povas kuri plej rapide.',
    'Mi povas iri al la luno en ĉirkaŭ 1.3 sekundoj.',
    'Mi estas bela, granda kaj konusa.',
    'Vi povas vidi min de Tokio en bela tago.',
    'Kelkfoje mi havas neĝon sur mia kapo.',
    'Mi estas tre bela.',
    'Oni amas mian ĉarman kaj enigman rideton.',
    'Mi estas belulino kun la plej ĉarma rideto.',
    'Mi loĝas en la muzeo en Parizo.',
    'Mi estas amata de multaj geknaboj en Japanio',
    'Ili povas vidi min sur televidilo.',
    'Mi estas forta, kaj aminda.',
    'Ĉu la ĉapo estas ĉapo de Taro?',
    'Kies estas la monero?',
    'Kies dentobroso?',
    'Kies estas la libro?',
    'Kies estas la krajono?',
    'Ĉu la plumo estas plumo de Miĉiko?',
    'Kiom da blokoj troviĝas?',
    'Kiom da kvadratoj?',
    'Kiom da trianguloj troviĝas?',
    'Kiom da trianguloj kaj kiom da kvadratoj?',
    'Nun estas la 6-a horo antaŭtagmeze en Tokio.',
    'Kioma horo nun estas?',
    'Kioma horo nun estas en Bagdado?',
    'Nun estas la 1-a horo atm. en Bagdado.',
    'Kiam Ĉefministro Kisida ellitiĝas je la 8-a atm. en Tokio.',
    'ĉu Prezidento Putin ankaŭ ellitiĝas en Moskvo?',
    'Ne! Ĉar kiam Kisida vekiĝas je la 8-a atm. en Tokio.',
    'La tempo en Moskvo estas 9-a horo.',
    'Kaj eble Putin estas ankoraŭ en la lito!',
    'Nun estas la 3-a horo atm. en Havajo.',
    'Kioma horo nun estas en Londono?',
    'Nun estas la 7-a horo ptm. en Tokio.',
    'Kioma horo nun estas en Novjorko?',
    'Nun estas la 11-a horo ptm. en Moskvo.',
    'Nun estas la 8-a atm. en Nov-Delio.',
    'Kioma horo nun estas en Tokio?',
    'Kurso de Esperanto',
    'Ŝi ŝatas legi librojn.',
    'Ŝi legas eĉ starante!',
    'La maljunulo ne povis ne trinki bieron,',
    'Mi volas manĝi.',
    'Donu al mi manĝaĵon, Panjo!',
    'Ŝi devas telefoni al li.',
    'Mi povas skii.',
    'Mi tre ŝatas surfrajdi.',
    'Ni sumou.',
    'Ek! Mi ne volas esti venkita.',
    'Mi ŝatas ludi kartojn kun Paĉjo.',
    'Brave!',
    'Mi povas rajdi biciklon.',
    'Rapide povas flugi Superhomo.',
    'Ili ŝatas baniĝi.',
    'Mi povas studi, aŭskultante muzikon.',
    'Mi ne volas supreniri ŝtuparon.',
    'Mi ne volas morti.',
    'Mi volas kisi vin.',
    'Ŝi ne ŝatas trinki.',
    'Ŝi devas trinki, ĉar ĝi estas laboro.',
    'Ĉu ŝi povas ludi tenison lerte?',
    'Ĉu vi scias, kion ĉi tiu vojmarko signifas?',
    'Jes, mi scias.',
    'La alfabeto P signifas parkejo, ĉu ne?',
    'Jes, prave.',
    'Ĉu vi scias ĉi tiun vojmarkon?',
    'Jes. Ĝi signifas, ke aŭtoj ne povas eniri.',
    'Jen alia vojmarko!',
    'Ĝi signifas, ke eble ŝtonoj falos.',
    'Mi demandas vin.',
    'Mi preparis strangajn bildojn.',
    'Do, diru al mi, kio estas eraro!',
    'La knabo skias per japanaj glavoj.',
    'Ĉu vi povas skii sen skibastonoj?',
    'Ŝi intencas ludi tenison, sed ĉu ŝi povas ludi tenison per basbala batilo?',
    'La instruisto skribas sur skribtabulo per tuĉpeniko sed ne per kreto.',
    'La knabo intencas manĝi bifstekon per kuirtranĉilo kaj manĝobastonetoj sed ne per tranĉilo kaj forko.',
    'Li ludas violonon per sago anstataŭ per kordo.',
    'Bonvolu sciigi al mi la vojon.',
    'Pardonon, s-ro Kon! Mi volas iri al Japana Ambasado.',
    'Ĉu vi bonvolus sciigi al mi la vojon tien?',
    'Jes, volonte! Marŝu tri stratblokojn laŭ ĉi tiu strato kaj turnu vin maldekstren.',
    'Vi trovos bankon maldekstre.',
    'Koran dankon!',
    'Ne, tute ne!',
    'Ĝis revido!',
    'Ĝis!',
    'Stetoskopo, Inter paciento kaj mi, Rideto!',
    'Malnova lageto, Rano saltas, Sono de Akvo',
    'Glaciaĵo, Ventumilo, ventotintilo, Ankoraŭ tro varme',
    'Venu kaj ludu, kun mi, paserido, Sen gepatroj',
    '80 Kmh, ĉe la angulo de okuloj, Azaleo floras!',
    'Mi simple esprimas jene : "Lageto Rano Plaŭd!"',
    'La aŭtoro devas esti bonkora homo.',
    'Li vidas sin mem en la birdeto.',
    'Mi neniam spertis tian tagon. Ne tolereble!',
    'Mi stiris aŭton sur aŭtovojo.',
    'Mi rimarkis belan floron dum la stirado.',
    'Mi estas doktoro.',
    'Mi ĝojas, ĉar ŝi iom resaniĝis.',
    'Pluvo refoje, Kontraŭ griza ĉielo, Ombreloj floras!',
    'Ni lernu per japana literaturo.',
    'Mi estas kato.',
    'Ankoraŭ nun mi ne havas nomon.',
    'Mi ne scias, kie mi naskiĝis.',
    'Ĉio, kion mi memoras, estas ke mi miaŭis en la malseka loko, kaj tiam mi vidis homon por la unua fojo.',
    'Antaŭ longa tempo, estis viro.',
    'Li fariĝis grave malsana.',
    'Kaj li konis en la koro ke li baldaŭ mortos.',
    'En la fino - ĉi vojon, ĉiuj homoj devas iri.',
    'Ĉi tion mi ĉiam konis, Sed hieraŭ aŭ hodiaŭ',
    'Ne! Neniam mi pripensis pri ĝi.',
    'Kiam la vojo komencis serpentumi kaj ŝajnis, ke la montopasejo.',
    'Amagi estas jam proksima.',
    'Pluvo postkuris min kun terura rapideco el la direkto de la montopiedo.',
    'Kolorante blanka la densan arbaron de kriptomerioj.',
    'Kiu vi estas?',
    'Kiu dato estas hodiaŭ?',
    'Kiu tago de la semajno hodiaŭ estas?',
    'Kiom da jaroj vi havas?',
    'Kiom da krajonoj vi havas nun?',
    'Kiom da geamikoj vi havas nun?',
    'Je kioma horo vi enlitiĝas?',
    'Kiam vi naskiĝis?',
    'Kio estas la unua tago de la semajno?',
    'Kiun manĝaĵon vi plej ŝatas?',
    'Kiom da homoj loĝas en Japanujo?',
    'Kion li faras nun?',
    'Kiun sporton vi ŝatas?',
    'Kiu estas prezidento de Usono?',
    'Kie okazis U.K. lastajare?',
    'Kie Zamenhof naskiĝis?',
    'Kio estas la ĉefurbo de Hispanujo?',
    'Kiun TV programeron vi plej ŝatas?',
    'Kien vi volas iri?',
    'Kie okazis U.K. en ĉi tiu jaro?',
    'Kies estas la banano?',
    'Feliĉo estas preĝi al Dio kun familianoj en vespero.',
    'Feliĉo estas ĝui sufiĉe longan dormadon en dimanĉa mateno.',
    'Feliĉo estas aŭskulti belegan muzikon.',
    'Feliĉo estas kanti laŭte en la banejo.',
    'Feliĉo estas revidi malnovajn amikojn en Universala Kongreso.',
    'Feliĉo estas kanti Simfonion Numeron 9 de Beethoven.',
    'Feliĉo estas kunligitaj manoj.',
    'Feliĉo estas ricevi leteron de nova amiko.',
    'Kio estas amo?',
    'Amo estas sunlumo, maro kaj freŝa aero.',
    'Amo estas alporti malgrandan lumon al la malsana amiko.',
    'Amo estas esperi, ke ŝi fartas bone.',
    'Amo estas iri kunkune mano en mano.',
    'Amo estas montogrimpado.',
    'Amo estas telefoni al malnova amiko.',
    'Amo estas marŝi kune en neĝo.',
    'Amo estas pacience elteni.',
    'Kartoludo por lerni verbojn',
    'Li kuras de Novjorko al Losanĝelo.',
    'La kato kun okulvitroj legas libron.',
    'Patro kaj filo ludas kartojn. Patrino servas teon.',
    'Li supreniras ŝtuparon.',
    'Mi ŝatas surfrajdi.',
    'Mi volas grimpi sur monton.',
    'Mi povas paŝi per manoj.',
    'Aŭskultante muzikon, li endormiĝas.',
    'Dankon, Esperanto!',
    'Nozomu vojaĝis en Eŭropo lastatempe.',
    'Jen estas lia parolado pri la vojaĝo.',
    'Mi vojagis en Portugalio, Hispanio, Italio, kaj Francio.',
    'La simileco de Esperanto al eŭropaj lingvoj mirigis min tre multe.',
    'Jen estas ekzemploj!',
    'Kiam mi deziras trinki mineralan akvon en Parizo, mi diras, "Eau mineral!"',
    'Kiam mi salutas dum la tago en Italio, mi diras, "Buon giorno!"',
    'En Portugalio mi diras, "Boa tarde!”',
    'En Esperantujo mi diras, "Bonan tagon!"',
    'Cu vi ne pensas, ke Esperanto tre similas al eŭropaj lingvoj?',
    'Mi ne sentis malfacilaĵon dum mia vojaĝo danke al Esperanto kaj Esperantistoj!',
    'Respondu en Esperanto!',
    'Kie Nozomu vojaĝis?',
    'Kio mirigis Nozomu dum la vojaĝo?',
    'Kio estas "sinjoro" en la hispana lingvo?',
    'Ĉu vi ne pensas, ke Esperanto similas al la franca lingvo?',
    'Itala ĉiĉerono klarigis al mi, "Vivocelo de italoj estas 「Mangiare, amore, kantare!」"',
    'Italoj laboras inter ludo kaj ludo.',
    'Japanoj ludas inter laboro kaj laboro.',
    'Ŝia klarigo ŝokis min, ĉar mi estas unu el "workaholics" (laboroholismo) vivantaj en kuniklejo.',
    'Kion mi pripensas nun estas, ke mi deziras ĝui mian vivon ne nur kiel "laboroholismo" sed ankaŭ kiel "ludoholismo".',
    'Kio estas vivocelo de italoj?',
    'Kio estas vivocelo de japanoj?',
    'Kio ja estas via vivocelo?',
    'Kiel vi pensas pri tio?',
    'Ĉu vi pensas ke japanoj estas treege laboremaj?',
    'Ĉu ferma ĉambro aŭ malfermita?',
    'Lerni kaj paroli nur patrinan lingvon estas kvazaŭ ni vivus en la ĉambro sen fenestroj nek pordoj.',
    'Ĝi estas malhela kaj fermita.',
    'Fremdaj lingvoj alportas novan lumon al la ĉambro.',
    'Ekzemple, lernantoj en Osaka ricevis leterojn kaj bildojn de svedaj lernantoj pere de la du esperantistaj instruistoj.',
    'Tiam japanaj lernantoj miris, ke svedaj infanoj pentris la sunon per flava koloro.',
    'Kvankam japanoj per ruĝa!',
    'Kaj se ni havas korespondantojn en diversaj landoj, ni povas havi rektan kontakton.',
    'Kaj se ni havas esperantistajn korespondantojn en diversaj landoj, ni povas scii diversajn aferojn.',
    'Kion alportas fremdaj lingvoj?',
    'Kial japanaj lernantoj miris?',
    'Ĉu vi loĝas en "la fermita ĉambro"?',
    'Aligato, aligatoro',
    'Mi estas aligatoro. Mia nomo estas Aligato.',
    'Mi loĝas en Paletro-Insulo.',
    'En Paletro-Insulo, multaj floroj floras.',
    'Paletro-Insulo estas tre bona insulo.',
    'Aligato nun legas libron.',
    'Iun tagon, Trombo ekestis abrupte.',
    'Trombo atakis kaj envolvis Aligaton.',
    'Turniĝas kaj turniĝas Trombo.',
    'Turniĝas kaj turniĝas la okuloj de Aligato!',
    'Vi vidu la okulojn de Aligato!',
    'Kiom da horoj pasis? Kie mi estas?',
    'Tamen iel mi estas ekster danĝero!',
    'Kun granda timo, Aligato malfermas la okulojn.',
    'Ŝtelrigardante suben, Aligato timegis.',
    'La okuloj de Aligato turniĝas!',
    'Kio estas “Aligato”?',
    'Kie li loĝas?',
    'Kio ekestis en la insulo?',
    'Kiuj turniĝas?',
    'La trombo atakis Aligaton, kaj kien ĝi forprenis Aligaton?',
    'En la sekvanta mateno helikoptero venis.',
    'Tio estas aligatoro!',
    'Ni iru tuj!',
    'Li estas tre malsana!',
    'Ni portu lin tuj!',
    'Malsana Aligato estas nun en hospitalo.',
    'Ĉi tiu aligatoro estas malsana!',
    'Li havas malaltan febron.',
    'Ni metu lin en la banujon!',
    'Jes, doktoro!',
    'Unuafoja baniĝo por Aligato!',
    'Mi estas finita!!',
    'En la sekvanta mateno, la dua doktoro venas.',
    'Ĉi tiu aligatoro estas malsata. Donu al li manĝaĵon!',
    'Jes, doktoro! Mi komprenas!',
    'Sed Aligato manĝis manĝaĵon kun telero.',
    'Li manĝis kaj manĝis kaj fariĝis malsana.',
    'Kio venis por savi Aligaton?',
    'Ĉu Aligato havis altan febron aŭ malaltan?',
    'Ĉu Aligato havis sperton baniĝi multefoje?',
    'Kiel la dua doktoro pensis pri Aligato?',
    'Kio okazis al Aligato post lia manĝado?',
    'En la sekvanta mateno, la tria doktoro venis.',
    'Ĉu tiu aligatoro volas promenadi, ĉu ne?',
    'Ankaŭ mi pensas tiel!',
    'Ni prenu lin por promenadi!',
    'Sur la strato estas multaj homoj kaj aŭtoj.',
    'Ankoraŭfoje turniĝas kaj turniĝas la okuloj de Aligato.',
    'Ankoraŭ Aligato estas malsana!',
    'Oni vidas artikolon pri Aligato en ĵurnalo.',
    'En iu tago, knabino vizitas Aligaton kun palmarbo.',
    'La okuloj de Aligato ekbrilis!',
    'Kiu venis en la sekvanta mateno?',
    'Kiel li pensis pri Aligato?',
    'Ĉu promenado plaĉis al Aligato?',
    'Kial turniĝis la okuloj de Aligato?',
    'Kion oni vidis en ĵurnalo?',
    'Kiu vizitis Aligaton en iu tago?',
    'Kiel Aligato sentis, vidante palmarbon?',
    'En la nokto, Aligato dormis trankvile kun malgranda palmarbo.',
    'Jes, mi komprenas!',
    'Povas esti, ke Aligato volas reveni hejmen.',
    'Ni sendu lin al Paletro-Insulo!',
    'La aviadilo estas super Paletro-Insulo!',
    'Ho, mia Paletro-Insulo! Koran dankon, piloto!',
    'Ne dankinde! Ĝis la revido, Aligato!',
    'Reveninte hejmen, Paletro-Insulo, Aligato skribas leteron al la knabino!',
    'Koran dankon, mia knabino! Ĝis la revido!',
    'Kial Aligato dormis trankvile en la nokto?',
    'Kion Aligato diris al la piloto?',
    'Kion Aligato faris post reveno al Paletro-lnsulo?',
    'Ĉu vi ŝatas Aligaton?',
    'Kiel vi pensas pri Aligato?',
    'Kio estas ĉi tio?',
    'Asuka instruas Esperanton al lernantoj.',
    'Do, mi demandas vin. Kio estas ĉi tio?',
    'Ĉu tio estas insekto?',
    'Ĉu mi povas manĝi tion?',
    'Ho, terure! Do, mi donas al vi ŝlosilon.',
    'Verŝajne, vi geknaboj ŝatas lin.',
    'Lin? Ĉu homo?',
    'Jes, aŭ ne!',
    'Mi donas al vi la duan ŝlosilon.',
    'Vi ofte vidas lin en televizia programo.',
    'Ĉu vi ŝatas lin, gvidanto?',
    'Mi komprenas! Tio estas "Doraemon”, ĉu ne?',
    'Vi pravas!',
    'Mi vidis lin de malsupre kaj desegnis lin.',
    'Aha, mi komprenas!',
    'Trafika Vojmarko',
    'Nozomu kaj Asuka alteme stiras aŭton.',
    'La du kaj Ŝahanni estas sur la vojo de Nagasaki.',
    'Asuka, vi stiras aŭton bele.',
    'Dankon, Ŝahanni!',
    'Ĉu vi volas stiri aŭton, Ŝahanni?',
    'Jes, mi volas.',
    'Mi havas intereson pri aŭto.',
    'Por gajni licencon pri stirado.',
    'Unue, vi devas legi la regularon por trafiko, Ŝahanni.',
    'Do, Ŝahanni, kion signifas la vojmarko tiea?',
    'Eble X signifas ke "Oni ne povas fari ion," ĉu ne?',
    'Jes, oni ne povas iri. "Vojo barita!"',
    'Ah, mi komprenas.',
    'Dankon, Nozomu.',
    'Kanĵi, Ĉina ideogramo',
    'Kion signifas ĉi tiu litero?',
    'La litero estas kanĵi, ĉina ideogramo kaj ĝi signifas monton.',
    '(Ilustrante) Ĉi-maniere la litero estis farita.',
    'Ŝahanni, ĉu vi scias. kion ĉi tiu kanĵi signifas?',
    'Do, mi donos al vi sugeston.',
    'En la litero ni vidas, ke du linioj subtenas unu la alian.',
    'Unu ne povas vivi sen la alia.',
    'Same kiel ni!',
    'Ho, mi komprenas!',
    'Ĝi estas "homo", ĉu ne?',
    'Prave dirita.',
    'Ĉu vi scias la signifon de tiu litero，Ŝahanni?',
    'Koŝien-Stadiumo',
    'Nozomu kaj Asuka kondukas Ŝahanni al Koŝien-Stadiumo.',
    'Mi neniam vidis ĉi tiom multajn homojn.',
    'Kiuj teamoj intermatĉas?',
    'Kompreneble "Hanŝin-Tigroj" kaj "Jomiuri-Gigantoj"!',
    'Ĉu basbalo ne estas populara en via lando?',
    'Ne. Mi vidas megafonojn, kiuj aspektas kvazaŭ flavaj floroj.',
    'Kion favorantoj diras?',
    'Ili diras, "Batu, Bass! Batu, Bass!”',
    'Mi vidas multajn balonetojn kaj...',
    'Kio estas tio?',
    'Kiam Hanŝin estas en la 7-a atako, ili flugigas balonetojn por kuraĝigi ludantojn de Hanŝin.',
    'Ankaŭ mi preparis balonetojn!',
    'Asuka, kial Nozomu kuraĝigas Hanŝin kun entuziasmo?',
    'Eble ĉar li naskiĝis en la jaro de “tigro” laŭ la antikva orienta kalendaro.',
    'Kie ili nun estas?',
    'Ĉu basbalo estas populara en Hindujo?',
    'Kio aspektas kvazaŭ flavaj floroj?',
    'Kion Nozomu preparis?',
    'Ĉu vi havas intereson pri basbalo?',
    'Kiel vi pensas pri "Tigroj-febro" de la lasta jaro?',
    'Fuĵi-Santaro',
    'Nozomu ekridas, legante karikaturon en "ĵurnalo Asahi”.',
    'Kial vi ridas, Nozomu?',
    'Ĉar ĉi tio estas ridiga kaj...',
    'Kaj ĉar Nozomu en jarfina kaj novjaraj tagoj tre similas al Fuĵi-Santaro, la heroo de la karikaturo.',
    'Kia karikaturo?',
    'Montru al mi.',
    'Jen estas!',
    'Ŝahanni ankoraŭ ne lernas "kanaon".',
    'Mi klarigu la enhavon.',
    'Ne skribante novjarajn kartojn, Santaro malŝparas tempon.',
    'Santaro malŝparas tempon, drinkante kaj rigardante televidan programon en jarfina tago.',
    'Li ankoraŭ drinkas kaj televidas en la mateno de novjara tago.',
    'Post kelkaj tagoj,li komencas skribi kartojn.',
    'Li faras la samon ĉiujare.',
    'La tempo por enpoŝtigi kartojn jam pasas.',
    'Tial li mem devas distribui la kartojn al la adresatoj.',
    'Kion Santaro faras en jarfina tago?',
    'Ĉu li estas drinkemulo?',
    'Kion lia filino diras al Santaro?',
    'Kiam li komencas skribi novjarajn kartojn?',
    'Kiel vi pensas pri Santaro?',
    'Ĉu vi similas al li?',
    'Donu al mi vian opinion.',
    'Matias, Germana Amiko',
    'Matias Voth, Germano, kiu estas leteramiko de Asuka, vizitas ilin.',
    'Li vojaĝas en Japanio utiligante pasportan servon.',
    'Asuka preparas banon.',
    'Matias, bano estas preparita.',
    'Bonvole baniĝu.',
    'Dankon, Anjo!',
    'Bano rememorigas al mi malbonan sperton pri bano.',
    'Kia sperto?',
    'Mia amiko en Tokio, s-ro Saito, gastigis min en sia hejmo.',
    'Ankaŭ li preparis banon por mi.',
    'Kaj kio okazis?',
    'Mi ĝuis banon, sed post unu horo en la banejo s-ino Saito demetis vestaĵon kaj ŝi surpriziĝis.',
    'Ahem! Mi komprenas vin, Matias.',
    'Vi malplenigis la akvon en la banujo, ĉu ne?',
    'Trafe!',
    'En Romo vivu romane!',
    'Ne! "En Japanujo vivu japane!"',
    'Ĉu Asuka havas leteramikon?',
    'Kion Asuka preparis por Matias?',
    'Ĉu Matias havas nebonan sperton pri bano?',
    'Kial s-ino Saito surpriziĝis en la banejo?',
    'Ĉu vi havas leteramikon en alilandoj?',
    'Ĉu vi iam utiligis pasportan servon?',
    'Nenio por manĝi',
    'Post baniĝo ili altabliĝas.',
    'Bongustaĵo estas sur la tablo.',
    'Ni havas nenion por manĝi, sed bonvole manĝu!',
    'Asuka, vi devas diri alimaniere.',
    'Ekzemple, "Mi esperas, ke mia kuiraĵo plaĉos al vi. Bonvole manĝu!"',
    'Ĉar se troviĝas nenio por manĝi, kiel Matias povas manĝi?',
    'Parolu logike!',
    'Asuka, ne zorgu pri tio.',
    'Iom post iom mi alkutimiĝas al japanaj modestaj esprimoj kaj manieroj.',
    'Vi japanoj ofte uzas modestan esprimon, ĉu ne?',
    'En la komencaj tagoj en via lando mi estis embarasita de la enigma japana esprimo.',
    'Vi diras antaŭ bongustaĵo, "Ni havas nenion por manĝi, sed bonvole manĝu!”',
    'Aŭdinte tion, mi sentis, "Se estas nenio por manĝi, ni iru al restoracio."',
    'Sed mi komprenas vin, Anjo!',
    'Ĉu bongustaĵo estas sur la tablo?',
    'Kion Asuka diris al Matias?',
    'Kiel Nozomu admonis al Asuka?',
    'Ĉu Matias komprenas japanan modestan esprimon nun?',
    'Kiel vi pensas pri japanaj modestaj esprimo kaj maniero?',
    'Tio estas “Honda” , ”Toyota” , “Sony” , “Fujijama” ,“Saŝimi” kaj “Geiŝa”.',
    'Mi legis unu libron, kiun NHK publikigis.',
    'Kio estas "Oŝija"?',
    'Se vi iras al stacidomo en svarma horo, vi povas vidi multajn homojn kaj puŝistojn.',
    'La puŝistoj estas la oficistoj, kiuj plenŝtopas trajnon per pasaĝeroj.',
    'Ĉu pasaĝeroj ne sentas doloron kiam ili estas puŝatai sur la dorso?',
    'ĉu ne estas sufokiga en la trajno?',
    'Kompreneble, jes.',
    'Sed ni eltenas.',
    'Kiam iu oficistino estis elvagoniĝonta, ŝi trovis, ke ŝi perdis sian ŝuon kun alta kalkanumo.',
    'Terure ！',
    'Klarigu al mi, kio estas "Oŝija"?',
    'Ĉu vi havas la saman sperton, kiun la oficistino havis en la trajno?',
    'Kiel vi pensas pri imago pri Japanujo en aliaj landoj?',
    'Ĉu vi iam prenis Ŝinkansen, Matias?',
    'Kompreneble, jes!',
    'Mi rimarkis en Ŝinkansen, ke pluveroj sur fenestro falas oblikve.',
    'Tio mirigis min.',
    'Japanaj aviadiloj, fervojoj, subteraj trajnoj, aŭtobusoj estas tre akurataj.',
    'Kiam ni antaŭe prenis ĉinan aviadilon, forlasis la Flughavenon Oosaka unu horon malfrue.',
    'Finfine atingis la Flughavenon Pekino tri horojn malfrue.',
    'Tio estas neimagebla afero en mia lando.',
    'Poste mi trovis la artikolon en gvidlibro en Ĉinio, ke Civil-Aviadila Administracio de Ĉinio estas aviada kompanio.',
    'Poste mi trovis la artikolon, ke CAAC estas aviada kompanio kun la plej malmultaj akcidentoj.',
    'Ĉar pilotarto estas altnivela kaj aviadilo neniam ekflugas en malbona vetero kaj kun nesufiĉa bontenado.',
    'Sekureco la unua kaj akurateco la dua, ĉu ne?',
    'Jes! En Japanujo akurateco la unua, sekureco la dua, ĉu?',
    'Kion Matias rimarkis en Ŝinkansen?',
    'Kiel vi pensas pri akurateco kaj sekureco de aviadilo en Japanio kaj Ĉinio?',
    'La ĉina aviadilo, kiu prenis Nozomu kaj Asuka, atingis la Flughavenon Pekino 2 horojn malfrue.',
    'La rapideco de ŝinkansen ne tiel mirigis Matias.',
    'Gvidlibro pri vojaĝo en Ĉinio diras, ke CAAC estas aviada kompanio, kiu havas la plej malmultajn akcidentojn.',
    'Hodiaŭ mi volas ludi kun vi “20 ŝlosilojn".',
    'Kio estas "20 Ŝlosiloj"?',
    'Mi klarigu.',
    'Nun mi imagas ion.',
    'Vi povas demandi per la demando, “Ĉu estas ~?”',
    'Mi respondas per “Jes!” aŭ “Ne!”',
    'Vi ne povas demandi, "Kio estas ĝi?”',
    'Vi, unu post la alia, povas demandi min.',
    'Tamen, la limo de permesata nombro de la demandoj estas 20.',
    'Vi devas trafi per almenaŭ 20 demandoj.',
    'Do, ni komencu! Manjo, vi estas la unua.',
    'Jes … Ĉu gi estas besto?',
    'Ĉu homo?',
    'Ĉu planto?',
    'Ĉu iu objekto?',
    'Ĉu ĝi troviĝas en ĉi tiu ĉambro?',
    'Ĉu mi povas trinki gin?',
    'Ĉu manĝebla?',
    'Ne! Vi, manĝegemulo, Joĉjo.',
    'Ĉu ĝi estas tablo?',
    'Ĉu krajono?',
    'Ne. Vi jam faris 10 demandojn.',
    'Ĉu ĝi koncernas Esperanton?',
    'Cu libro de Esperanto?',
    'Ĉu vi ŝatas?',
    'Ĉu ĝi estas utila por vi?',
    'Jes. Por mi kaj por esperantistoj.',
    'Verda standardo?',
    'Ĉu verda stelo?',
    'Ne, sed tre proksime.',
    'Ĉu vi havas ĝin?',
    'Jes, mi havas aŭ surmetas ĝin nun.',
    'Ĉu ĝi estas pli granda ol ĉi tiu vortaro de Esperanto?',
    'Ĉu ronda?',
    'Jes. La sekvanta demando estas la lasta!',
    'Ĉu?... Ah, mi komprenas! Ĝi estas insigno de Esperanto ĉu ne?',
    'Jes, trafite!',
];
