K_course = [
	'Bonvole donu al mi akvon.',
	'Bonvole donu al mi monon.',
	'Bonvole donu al mi liberon.',
	'Bonvole donu al mi la libron.',
	'Bonvole donu al mi vian konsilon.',
	'Bonvole donu al mi panon.',
	'Bonvole sidiĝu. Bonvolu sidiĝi.',
	'Bonvole manĝu. Bonvolu manĝi.',
	'Bonvole aŭskultu. Bonvolu aŭskulti.',
	'Bonvole parolu. Bonvolu paroli.',
	'Bonvole iru. Bonvolu iri.',
	'Bonvole stariĝu. Bonvolu stariĝi.',
	'(Vi) Iru for.',
	'Venu al mi morgaŭ.',
	'Manĝu multe.',
	'Diru al mi la veron.',
	'Venu rapide.',
	'Estu trankvila.',
	'Ne ploru.',
	'Ne tuŝu (ĝin).',
	'Ne zorgu (pri tio).',
	'Ne forĵetu (ĝin).',
	'Ne koleru.',
	'Ne ridu.',
	'Bonvole demandu ŝin.',
	'Bonvole demandu ŝin pri tio.',
	'Bonvole demandu ŝin, ĉu ŝi venos (aŭ ne).',
	'Bonvole demandu ŝin, kio ĝi estas.',
	'Ĉu ĝi estas bongusta?',
	'Jes, ĝi estas bongusta.',
	'Ĉu ĝi estas interesa?',
	'Jes, ĝi estas interesa.',
	'Ĉu ĝi estas bona?',
	'Jes, ĝi estas tre bona.',
	'Ĉu ĝi estas malfacila?',
	'Jes, ĝi estas tre malfacila.',
	'Ĉu ĝi estas peza?',
	'Ne, ĝi ne estas tiel peza.',
	'Ĉu ĝi estas bela?',
	'Ne, ĝi ne estas tiel bela.',
	'Ĉu ili estas belaj?',
	'Jes, ili estas belaj.',
	'Ne, ili ne estas belaj.',
	'Ĉu ili estas fortaj?',
	'Jes, ili estas fortaj.',
	'Ne, ili ne estas fortaj.',
	'Ĉu li estas diligenta?',
	'Jes, li estas diligenta.',
	'Ne, li ne estas diligenta.',
	'Ĉu ŝi estas bonkora?',
	'Jes, ŝi estas bonkora.',
	'Ne, ŝi ne estas bonkora.',
	'Ĉu ĝi estas libro?',
	'Jes, ĝi estas libro.',
	'Ne, ĝi ne estas libro.',
	'Ĉu ĝi estas via libro?',
	'Jes, ĝi estas mia libro.',
	'Ne, ĝi ne estas mia libro.',
	'Ĉu ĝi estas la domo?',
	'Jes, ĝi estas la domo.',
	'Ne, ĝi ne estas la domo.',
	'Ĉu ĝi estas via lernejo?',
	'Jes, ĝi estas mia lernejo.',
	'Ne, ĝi ne estas mia lernejo.',
	'Ĉu ĝi estas facila demando?',
	'Jes, ĝi estas facila demando.',
	'Ne, ĝi ne estas facila demando.',
	'Ĉu ĝi estas multekosta vesto?',
	'Jes, ĝi estas multekosta vesto.',
	'Ne, ĝi ne estas multekosta vesto.',
	'Ĉu ĝi estas pano?',
	'Jes, ĝi estas pano.',
	'Ne, ĝi ne estas pano.',
	'Ĉu ĝi estas frukto?',
	'Jes, ĝi estas frukto.',
	'Ne, ĝi ne estas frukto.',
	'Ĉu ĝi estas bongusta frukto?',
	'Jes, ĝi estas bongusta frukto.',
	'Ne, ĝi ne estas bongusta frukto.',
	'Ĉu ĝi estas blanka aŭto?',
	'Jes, ĝi estas blanka aŭto.',
	'Ne, ĝi ne estas blanka aŭto.',
	'Ĉu ĝi ne estas via sako?',
	'Ĉu ŝi ne estas lia fratino?',
	'Ĉu ĝi ne estas la restoracio?',
	'Ĉu ĝi ne estas mia mono?',
	'Ĉu ĝi ne estas bona?',
	'Ĉu ĝi ne estas multekosta?',
	'Ĉu li ne estas bona amiko?',
	'Ĉu vi ne estas okupita?',
	'Ĉu vi ne estas lia amiko?',
	'Ĉu ŝi ne estas via patrino?',
	'Ĉu mi devas renkonti lin?',
	'Jes, vi devas renkonti lin.',
	'Ĉu mi devas manĝi ĝin?',
	'Jes, vi devas manĝi ĝin.',
	'Ĉu mi devas skribi leteron?',
	'Jes, vi devas skribi leteron.',
	'Ĉu mi devas voki ŝin?',
	'Jes, vi devas voki ŝin.',
	'Ĉu vi devas ekiri nun?',
	'Jes, mi devas ekiri nun.',
	'Ĉu vi devas reveni hejmen?',
	'Jes, mi devas reveni hejmen.',
	'Ĉu li devas iri kun ni?',
	'Jes, li devas iri kun ni.',
	'Ĉu ŝi devas reveni al lernejo?',
	'Jes, ŝi devas reveni al lernejo.',
	'Ĉu ili devas aĉeti ĝin?',
	'Jes, ili devas aĉeti ĝin.',
	'Ĉu ili devas lerni Esperanton?',
	'Jes, ili devas lerni Esperanton.',
	'Ĉu mi povas viziti vin?',
	'Ĉu mi povas demandi vin?',
	'Ĉu mi povas kuniri kun vi?',
	'Ĉu mi povas prezenti ŝin al vi?',
	'Ĉu vi povas tuj veni al mi?',
	'Ĉu vi povas helpi min?',
	'Ĉu vi povas esti pli afabla?',
	'Ĉu vi povas malfermi la pordon?',
	'Ĉu li povas manĝi ĝin?',
	'Ĉu li povas telefoni al ŝi?',
	'Ĉu li povas kuri tiel rapide?',
	'Ĉu li povas promesi tion?',
	'Ĉu ŝi povas sekvi lin?',
	'Ĉu ŝi povas obei la patron?',
	'Ĉu ŝi povas permesi tion al li?',
	'Ĉu ŝi povas nuligi tion?',
	'Ĉu ili povas respondi al vi?',
	'Ĉu ili povas interkonsenti pri tio?',
	'Ĉu ili povas vojaĝi kune?',
	'Ĉu ili povas diri tion?',
	'Ĉu vi estas malsata?',
	'Jes, mi estas malsata.',
	'Ĉu vi estas kolera?',
	'Jes, mi estas kolera.',
	'Ĉu vi estas diligenta?',
	'Jes, mi estas diligenta.',
	'Ĉu vi estas feliĉa?',
	'Ne, mi ne estas feliĉa.',
	'Ĉu vi estas malsana?',
	'Ne, mi ne estas malsana.',
	'Ne, li ne estas interesa.',
	'Ne, ŝi ne estas bela.',
	'Ĉu vi estas kontenta?',
	'Jes, mi estas kontenta.',
	'Ne, mi ne estas kontenta.',
	'Ĉu li estas bonkora?',
	'Jes, li estas bonkora.',
	'Ne, li ne estas bonkora.',
	'Ĉu vi ŝatas danci?',
	'Jes, mi ŝatas danci.',
	'Ĉu vi ŝatas kanti?',
	'Jes, mi ŝatas kanti.',
	'Ĉu vi ŝatus iri kun mi?',
	'Jes, volonte. Mi iros kun vi.',
	'Ĉu vi ŝatus pruntedoni ĝin al mi?',
	'Jes, mi pruntedonos ĝin al vi.',
	'Ĉu li ŝatas ludi pianon?',
	'Ĉu li ŝatas babili kun amikoj?',
	'Ĉu li ŝatas montogrimpi?',
	'Ĉu li ŝatas ludi tablotenison?',
	'Ĉu ŝi ŝatus iri kun vi?',
	'Eble jes, sed mi ne certas.',
	'Ĉu ŝi ŝatus interparoli kun li?',
	'Eble ne. Ŝi ŝatus interparoli kun lia frato.',
	'Ĉu Petro ŝatas ludi korbopilkon?',
	'Ĉu Maria ŝatas ludi badmintonon?',
	'Ĉu via amiko ŝatas manĝi legomojn?',
	'Ĉu viaj gepatroj ŝatas vojaĝi?',
	'Ĉu vi ŝatas ĝin?',
	'Ĉu vi ŝatas tion?',
	'Ĉu vi ŝatas lin?',
	'Ĉu vi ŝatas ŝin?',
	'Ĉu li ŝatas muzikon?',
	'Jes, li ŝatas muzikon.',
	'Ĉu ŝi ŝatas dancon?',
	'Ne, ŝi ne ŝatas dancon.',
	'Ĉu ili ŝatas fruktojn?',
	'Ĉu ili ŝatas pomon?',
	'Ĉu ili ŝatas ĉinajn manĝaĵojn?',
	'Ĉu ili ŝatas viandon?',
	'Ĉu ili ŝatas nudelon?',
	'Ĉu vi ne ŝatas ĉokoladon?',
	'Ĉu vi ne ŝatas vintron?',
	'Ĉu vi ŝatas tion aŭ ĉi tion?',
	'Mi ŝatas ĉi tion.',
	'Ĉu vi ŝatas lin aŭ lian fraton?',
	'Mi ŝatas lian fraton.',
	'Ĉu vi volas danci?',
	'Ĉu vi volas kanti?',
	'Ĉu vi volas ludi gitaron?',
	'Ĉu vi volas manĝi?',
	'Ĉu li volas lerni Esperanton?',
	'Ĉu li volas vojaĝi kun vi?',
	'Ĉu li volas reveni hejmen?',
	'Ĉu li volas edziĝi kun ŝi?',
	'Ĉu ŝi ne volas kuiri?',
	'Ĉu ŝi ne volas viziti lin?',
	'Ĉu ŝi ne volas iri kun li?',
	'Ĉu ŝi ne volas ricevi ĝin?',
	'Ĉu ili volas renkonti lin?',
	'Ĉu ili volas konfesi tion?',
	'Ĉu ili volas kaŝi tion?',
	'Ĉu ili volas nuligi tion?',
	'S-ro Sun volas vidi ĝin.',
	'S-ino Liu volas paroli kun vi.',
	'Gesinjoroj Li volas viziti Pekinon.',
	'Fraŭlino Zhang volas kanti.',
	'Saluton.',
	'Kiel vi fartas?',
	'Mi fartas bone, kaj vi?',
	'Dankon. Ankaŭ mi fartas bone.',
	'Bonan matenon.',
	'Bonan tagon.',
	'Bonan vesperon.',
	'Bonan nokton.',
	'Bonan sonĝon.',
	'Ĝis revido. Ĝis (la).',
	'Adiaŭ.',
	'Multan dankon.',
	'Ne dankinde.',
	'Pardonon.',
	'Ne gravas.',
	'Bonvole.',
	'Esperantisto',
	'Bone.',
	'Malbone.',
	'Bonan apetiton.',
	'Bonan vojaĝon.',
	'Bonan laboron.',
	'Bone fartu.',
	'Gratulon.',
	'Por via sano. Je via sano.',
	'Atenton. Atentu.',
	'Jen estas belaj floroj.',
	'Jen estas floro.',
	'Jen estas floroj.',
	'Jen estas bela floro.',
	'Mi havas belan floron.',
	'Mi havas belajn florojn.',
	'Jen estas interesa libro.',
	'Ĝi estas interesa libro.',
	'Jen estas interesaj libroj.',
	'Ili estas interesaj libroj.',
	'Mi havas interesan libron.',
	'Mi havas interesajn librojn.',
	'La libro estas interesa.',
	'La libroj estas interesaj.',
	'Li estas honesta.',
	'Ŝi estas honesta.',
	'Ili estas honestaj.',
	'Vi estas honesta.',
	'Mi amas honestan homon.',
	'Mi amas honestajn homojn.',
	'Li estas feliĉa.',
	'Ili estas feliĉaj.',
	'Ĉiuj amas feliĉan vivon.',
	'Ĉiuj ŝatas honestan amikon.',
	'Ĉiuj ŝatas dolĉajn manĝaĵojn.',
	'Jen estas biciklo.',
	'Tie estas motorbiciklo.',
	'Ĉu tie estas motorbiciklo?',
	'Jes, tie estas motorbiciklo.',
	'Kia estas Zaozhuang?',
	'Ĝi estas tre bela.',
	'Kia urbo estas Zaozhuang?',
	'Ĝi estas bela urbo.',
	'Kia estas Esperanto?',
	'Ĝi estas interesa kaj facila.',
	'Kian libron vi legis?',
	'Mi legis tre interesan libron.',
	'Kian homon vi ŝatas?',
	'Mi ŝatas afablan homon.',
	'Kia estas via amiko, Marko?',
	'Li estas bona.',
	'Kiaj estas la studentoj?',
	'La studentoj estas tre diligentaj.',
	'Kia estas la knabino?',
	'La knabino estas egoisma.',
	'Kiajn librojn vi kolektas?',
	'Mi kolektas historiajn librojn.',
	'Kian opinion vi havas pri tio?',
	'Mi havas pozitivan opinion pri tio.',
	'Kian amikinon vi volas havi?',
	'Mi volas havi bonkoran amikinon.',
	'Kian manĝaĵon vi amas?',
	'Mi amas dolĉan manĝaĵon.',
	'Kial vi ridas?',
	'Kial vi ploras?',
	'(Mi ploras,) Ĉar mi estas malĝoja.',
	'Kial vi estas malĝoja?',
	'(Mi estas malĝoja,) Ĉar mi perdis monon.',
	'(Mi ridas,) Ĉar mi ĝojas.',
	'Kial vi ĝojas?',
	'(Mi ĝojas,) Ĉar mi retrovis la monon.',
	'Kial vi iras al lernejo?',
	'Mi iras al lernejo por lerni Esperanton.',
	'Kial vi ne manĝas ĝin?',
	'(Mi ne manĝas ĝin,) Ĉar ĝi ne estas bongusta.',
	'Kial vi batas vian fraton?',
	'(Mi batas lin,) Ĉar li ne obeas min.',
	'Kial li amas ŝin?',
	'(Li amas ŝin,) Ĉar ŝi estas tre afabla.',
	'Kial vi ne laboras?',
	'(Mi ne laboras,) Ĉar mi ne havas laboron.',
	'Kial li ne revenas hejmen?',
	'(Li ne revenas hejmen,) Ĉar li ne havas domon.',
	'Kiam vi venos?',
	'Mi venos morgaŭ.',
	'Kiam li alvenos?',
	'Li alvenos baldaŭ.',
	'Kiam ili venos?',
	'Ili venos postmorgaŭ.',
	'Kiam vi mantenmanĝas?',
	'Mi matenmanĝas je la sepa (horo).',
	'Kiam vi tagmanĝas?',
	'Mi tagmanĝas je la dek-dua (horo).',
	'Kiam vi vespermanĝas?',
	'Mi vespermanĝas je la sesa (horo).',
	'Kiam vi ekiros?',
	'Mi ekiros je la naŭa (horo).',
	'Kiam ŝi edziniĝos?',
	'Ŝi edziniĝos post unu jaro.',
	'Kiam finiĝas via klaso?',
	'Ĝi finiĝas je la 11-a kaj 45.',
	'Kiam mi venu al vi?',
	'Je la 12-a (horo) venu al mi.',
	'Kiam vi renkontos ŝin?',
	'Mi renkontos ŝin je la tria (horo).',
	'Kiam komenciĝas via lernejo?',
	'Mia lernejo komenciĝas je la oka matene.',
	'Kian aĝon vi havas? Kia estas via aĝo? Kioman aĝon vi havas?',
	'Mi estas dudek-jara.',
	'Mi havas dudek unu jarojn.',
	'Mia aĝo estas dudek tri.',
	'Kian aĝon havas ŝi? Kiom ŝi aĝas?',
	'Ŝi havas dek naŭ jarojn.',
	'Kia estas lia aĝo?',
	'Lia aĝo estas dudek. Li havas dudek jarojn. Li estas dudek-jara.',
	'Lia aĝo estas dudek unu.',
	'Li estas dudek-unu-jara.',
	'Li aĝas tridek jarojn.',
	'Kioman aĝon havas via patro?',
	'Li havas 50 jarojn.',
	'En tiu ĉi jaro kian aĝon havas via filo?',
	'En tiu ĉi jaro li havas 9 jarojn.',
	'Ŝi aĝas kvardek jarojn.',
	'Kie estas via hejmloko?',
	'Kie estas via amiko?',
	'Li estas en la klasoĉambro.',
	'Kie estas via poŝtelefono?',
	'Ĝi estas sur la tablo.',
	'Kie estas Dio?',
	'Dio estas en nia koro.',
	'Kie estas Ĉinio?',
	'Ĉinio estas en Azio.',
	'Kie estas via ĉapo?',
	'Ĝi estas tie sur la seĝo.',
	'Kie estas la hundo?',
	'Ĝi estas sub la arbo.',
	'Kie estas via komputilo?',
	'Ĝi estas en mia ĉambro.',
	'Kie estas necesejo?',
	'Ĝi estas tie maldekstre.',
	'Kie estas viaj libroj?',
	'Ili estas sur la tablo.',
	'Kie estas via universitato?',
	'Ĝi estas en la urbo Zaozhuang.',
	'Kie vi estas?',
	'Mi estas en lernejo.',
	'Kie estas via hejmo?',
	'Mia hejmo estas en Linyi.',
	'Ĝi estas tie.',
	'Kie vi loĝas?',
	'Mi loĝas en la lernejo.',
	'Kie loĝas viaj gepatroj?',
	'Ili loĝas en Ŝanhajo.',
	'Kie vi manĝas?',
	'Mi manĝas en la manĝejo.',
	'Kie vi dormas?',
	'Mi dormas en la ĉambro.',
	'Kie ludas la infanoj?',
	'Ili ludas en la parko.',
	'Kie ŝi ripozas?',
	'Ŝi ripozas sur la lito.',
	'Kie vi lernas Esperanton?',
	'Mi lernas ĝin en mia lernejo.',
	'Mi dormas en dormĉambro.',
	'Kie vi studas?',
	'Mi studas en klasoĉambro.',
	'Kie vi naskiĝis?',
	'Mi naskiĝis en Pekino.',
	'Kie vi vidis ŝin?',
	'Mi vidis ŝin en la biblioteko.',
	'Dankon, mi fartas bone.',
	'Kiel li fartas?',
	'Kiel vi fartas nuntempe?',
	'Nuntempe mi fartas bone.',
	'Kiel vi fartis intertempe?',
	'Intertempe mi fartis bone.',
	'Kiel ŝi fartas?',
	'Ŝi fartas tre bone.',
	'Kiel ili fartas?',
	'Ili fartas malbone.',
	'Kiel fartas via edzino?',
	'Dankon, ŝi fartas bone.',
	'Kiel fartas viaj familianoj?',
	'Dankon, ili fartas tre bone.',
	'Dankon, mi fartis tre bone.',
	'Dankon, sed mi fartis iom malbone.',
	'Kial? Pro kio?',
	'(Ĉar) Mi malvarmumiĝis.',
	'Kien vi iras?',
	'Mi iras al hejmo.',
	'Mi iras al lernejo.',
	'Kien li iras?',
	'Li iras al Pekino.',
	'Li iras tien.',
	'Kien ŝi iras?',
	'Ŝi iras al la domo de ŝia amiko.',
	'Kien ŝi iras nun?',
	'Nun ŝi iras al manĝejo.',
	'Kien ili iris hieraŭ?',
	'Hieraŭ ili iris al monto.',
	'Kien kuris la rato?',
	'La rato kuris sub la liton.',
	'Kien vi iris hieraŭ posttagmeze?',
	'Hieraŭ posttagmeze mi iris al la biblioteko.',
	'Kien kuras la kato?',
	'Ĝi kuras sub la liton.',
	'Kies libro ĝi estas?',
	'Kies sako ĝi estas?',
	'Ĝi estas lia sako.',
	'Kies mono ĝi estas？',
	'Ĝi estas mia mono.',
	'Kies libroj ili estas?',
	'Ili estas ŝiaj libroj.',
	'Kies libron vi legas?',
	'Mi legas lian libron.',
	'Kies pianon ŝi ludas?',
	'Ŝi ludas la pianon de sia amiko.',
	'Kies prononco estas ĝusta?',
	'Lia prononco estas ĝusta.',
	'Kies vortoj estas veraj?',
	'Ŝiaj vortoj estas veraj.',
	'Kun kies amikoj vi ludas?',
	'Mi ludas kun liaj amikoj.',
	'Per kies skribilo vi skribas?',
	'Mi skribas per ŝia skribilo.',
	'Kio ĝi estas?',
	'Ĝi estas libro. Ĝi estas mia libro.',
	'Ĝi estas floro. Ĝi estas bela floro.',
	'Kion vi legas?',
	'Mi legas libron. Mi legas interesan libron.',
	'Kion vi vidas?',
	'Mi vidas arbon.',
	'Mi vidas grandan arbon.',
	'Kion vi manĝas?',
	'Mi manĝas nudelon.',
	'Kio estas amo?',
	'Amo estas intereso kaj prizorgo.',
	'Kio estas Esperanto?',
	'Ĝi estas internacia lingvo.',
	'Kio estas via nomo?',
	'Mia nomo estas Petro.',
	'Kion vi diras?',
	'Mi diras nenion.',
	'Kion vi skribas.',
	'Mi skribas mian nomon.',
	'Kion ŝi diris?',
	'Ŝi diris, ke ŝi amas lin.',
	'Kion li diras?',
	'Li diras, ke li ne amas ŝin.',
	'Kio estas la vero?',
	'Kiom ĝi kostas?',
	'Ĝi kostas cent juanojn.',
	'Kiom kostas la libro?',
	'Ĝi(La libro) kostas kvindek juanojn.',
	'Kiom kostas via ĉapo?',
	'Ĝi kostas dek du dolarojn.',
	'Kiom kostas la manĝaĵo?',
	'Ĝi kostas dudek juanojn.',
	'Kiom kostas la pomo?',
	'Unu pomo kostas unu eŭron.',
	'Kiom kostas la ŝuoj?',
	'Ili kostas okdek dolarojn.',
	'Kiom vi pagis por ĝi?',
	'Mi pagis (por ĝi) tridek dolarojn.',
	'Kiom vi pagis por la vespermanĝo?',
	'Mi pagis sesdek juanojn.',
	'Kiom mi devas pagi?',
	'Vi devas pagi dudek du eŭrojn.',
	'Kiom mi devas pagi por ĝi?',
	'Vi devas pagi cent tridek sep juanojn.',
	'Kioma horo nun estas?',
	'Nun estas la oka (horo) kaj dudek (minutoj).',
	'Nun estas kvin (minutoj) antaŭ la sepa (horo).',
	'(Nun) estas dek dua kaj duono.',
	'(Nun) estas naŭa kaj kvarono.',
	'Je kioma horo vi revenos?',
	'Mi revenos je la tria kaj duono.',
	'Je kioma horo alvenos la trajno?',
	'La trajno alvenos je la unua kaj dek.',
	'Kiom da horoj vi bezonas?',
	'Mi bezonas kvar horojn.',
	'Kiom da horoj vi laboris?',
	'Mi laboris ses horojn.',
	'Je kioma horo vi finos la laboron?',
	'Mi finos ĝin je la kvina posttagmeze.',
	'Kiom da minutoj mi devas atendi?',
	'Eble dek minutojn vi devas atendi.',
	'Mi vidas bildon.',
	'Mi legas libron.',
	'Mi manĝas panon.',
	'Kion li pensas?',
	'Li pensas pri lia amiko.',
	'Kion ŝi petas?',
	'Ŝi petas lian helpon.',
	'Kion ili sendis al vi?',
	'Ili sendis al mi librojn.',
	'Kion ili donis al ŝi?',
	'Ili donis al ŝi multan monon.',
	'Kion vi aŭdis?',
	'Mi aŭdis liajn vortojn.',
	'Kion vi rigardas?',
	'Mi rigardas la birdojn.',
	'Kiu vi estas?',
	'Mi estas Petro Sun.',
	'Kiu li estas?',
	'Li estas Marko.',
	'Li estas sinjoro Liu.',
	'Kiu ŝi estas?',
	'Ŝi estas Klara.',
	'Ŝi estas sinjorino Lin.',
	'Li estas mia onklo.',
	'Li estas Petro.',
	'Ŝi estas mia amikino.',
	'Ŝi estas Maria.',
	'Kiu estas la knabo?',
	'Li estas mia nevo.',
	'Kiu estas la sinjoro?',
	'Li estas mia instruisto.',
	'Kiu estas la virino?',
	'Ŝi estas mia najbaro.',
	'Kiuj estas la knaboj?',
	'Ili estas la amikoj de mia filo.',
	'Kiuj estas ili?',
	'Ili estas studentoj de tiu universitato.',
	'Kiu estas via amiko?',
	'Li (Tiu) estas mia amiko.',
	'Ŝi (Ĉi tiu) estas mia amikino.',
	'Kiun vi amas?',
	'Mi amas lin.',
	'Kiujn vi amas?',
	'Mi amas miajn gefratojn.',
	'Kiuj estas la sinjoroj?',
	'Ili estas la profesoroj de mia universitato.',
	'Kiun li amas?',
	'Li amas la (tiun) knabinon.',
	'Kiun li ŝatas?',
	'Li ŝatas ĉi tiun knabinon.',
	'Kiun ŝi amas?',
	'Ŝi amas la studenton en la klasoĉambro.',
	'Kiun ŝi ŝatas?',
	'Ŝi ŝatas la knabon tie.',
	'Kiu(j)n ili amas?',
	'Ili amas siajn fratojn.',
	'Kiun ili atendas?',
	'Ili atendas la novan instruiston.',
	'Kiun vi vidis tie?',
	'Tie mi vidis sinjoron Liu.',
	'Kiun vi renkontis hieraŭ?',
	'Hieraŭ mi renkontis mian amikinon.',
	'Li estas mia amiko.',
	'Ili estas miaj geamikoj.',
	'Ĉu li estas via amiko?',
	'Ĉu ŝi estas via amikino?',
	'Ĉu ili estas viaj geamikoj?',
	'Ne, ĝi ne estas mia libro, sed lia libro.',
	'Ĉu ĝi estas ŝia sako?',
	'Ne, ĝi ne estas ŝia sako, sed lia sako.',
	'Jen estas mia amiko, Tigro.',
	'Ĉu Tigro estas via amiko?',
	'Jes, li estas mia amiko.',
	'Mi amas vin.',
	'Ĉu vi amas min?',
	'Jes, mi amas vin.',
	'Ĉu ŝi amas lin?',
	'Jes, ŝi amas lin.',
	'Ili amas vin, kaj vi amas ilin.',
	'Mi amas Esperanton.',
	'Ĉu vi amas Esperanton?',
	'Jes, mi(ni) amas Esperanton.',
	'Ĉu ili lernas Esperanton?',
	'Ne, ili ne lernas Esperanton.',
	'Mi amas mian fraton.',
	'Ĉu vi amas vian fraton?',
	'Mi amas miajn amikojn.',
	'Ankaŭ li amas miajn amikojn.',
	'Miaj amikoj ankaŭ estas liaj amikoj.',
	'Mi amas mian patron.',
	'Mi amas mian patrinon.',
	'Mi amas miajn gepatrojn.',
	'Ĉu vi amas viajn gepatrojn?',
	'Jes, mi amas ilin.',
	'Mi amas ĉokoladon.',
	'Ĉu vi amas ĉokoladon?',
	'Mi amas mian patrolandon.',
	'Ĉu li amas hundon?',
	'Jes, li amas hundojn.',
	'Mi devas iri.',
	'Mi devas labori.',
	'Mi devas dormi.',
	'Mi devas renkonti lin.',
	'Vi devas viziti ŝin.',
	'Vi devas ne fari tion.',
	'Vi ne devas ludi kun li.',
	'Vi ne devas paroli tiel.',
	'Li devas tuj veni al mi.',
	'Li devis veni hieraŭ.',
	'Ŝi devas labori pli diligente.',
	'Ŝi devis helpi lin pli multe.',
	'Li devos konfesi la veron.',
	'Li devos manĝi pli malmulte.',
	'Ŝi devos fari ĝin sola.',
	'Ŝi devos kunlabori kun ili.',
	'Mi devos diri al ili la veron.',
	'Mi devos ree pensi pri tio.',
	'Vi devos fermi la okulojn.',
	'Vi devos silenti pri tio.',
	'Mi estas feliĉa.',
	'Mi estas malfeliĉa.',
	'Mi estas malĝoja.',
	'Mi estas alta.',
	'Mi estas dika.',
	'Mi estas forta.',
	'Mi estas sana.',
	'Vi estas tre afabla.',
	'Vi estas tre bela.',
	'Vi estas tre diligentaj.',
	'Li estas interesa.',
	'Li estas okupita.',
	'Ŝi estas fidinda.',
	'Ŝi estas laborema.',
	'Ĝi estas maldika.',
	'Ĝi estas malalta.',
	'Mi estas malalta.',
	'Ĝi estas multa.',
	'Ĝi estas bongusta.',
	'Esperanto estas interesa.',
	'Esperanto estas facila.',
	'Mi lernas Esperanton.',
	'Vi lernas Esperanton.',
	'Li lernas Esperanton.',
	'Ŝi lernas Esperanton.',
	'Ni lernas Esperanton.',
	'Ili lernas Esperanton.',
	'Esperanto estas internacia lingvo.',
	'Ĝi estas bona lingvo.',
	'Multaj homoj lernas Esperanton.',
	'Ĉu vi lernas Esperanton?',
	'Jes, mi lernas ĝin.',
	'Esperanto havas 28 literojn.',
	'Ĝia prononco estas tre facila kaj bela.',
	'Ĉu vi memoras la literojn?',
	'Jes, mi memoras ilin.',
	'Mi parolas en Esperanto.',
	'Ĉu vi parolas en Esperanto?',
	'Ili ankaŭ parolas en Esperanto.',
	'Bonvole parolu en Esperanto.',
	'Jes, mi parolos en Esperanto.',
	'Ĉu vi volas lerni Esperanton?',
	'Jes, mi volas lerni ĝin.',
	'Bonvole instruu al mi Esperanton.',
	'Li instruis al mi Esperaton.',
	'Mi povas kanti.',
	'Mi povas danci.',
	'Mi povas paroli en Esperanto.',
	'Mi povas kuri rapide.',
	'Mi povas telefoni al ŝi.',
	'Mi mem povas fari la hejmtaskon.',
	'Mi povas prezenti ŝin al vi.',
	'Mi povas skribi ĉinajn ideogramojn.',
	'Vi povas veni al mi morgaŭ.',
	'Vi povas renkonti ŝin.',
	'Vi povas manĝi ĝin.',
	'Vi povas sidiĝi tie.',
	'Li povos sukcesi.',
	'Li povis diri nenion.',
	'Ŝi povos diri al vi la veron.',
	'Ŝi ne povas manĝi multe.',
	'Li povis renkonti ŝin hieraŭ.',
	'Li povis kompreni ĝin.',
	'Ŝi povis senti danĝeron.',
	'Ŝi povis akiri laboron.',
	'Mi volas iri.',
	'Mi volas manĝi.',
	'Mi volas dormi.',
	'Mi volas ripozi.',
	'Ĉu vi volas vidi ĝin?',
	'Ĉu vi volas reveni hejmen?',
	'Ĉu vi volas renkonti ŝin?',
	'Li ne volas iri tien.',
	'Li ne volas sendi ĝin al vi.',
	'Li ne volas paroli kun ŝi.',
	'Li ne volas respondi al mi.',
	'Ĉu ŝi ne volas vidi vin?',
	'Ne, ŝi ne volas vidi min.',
	'Jes, ŝi volas vidi min.',
	'Ne, ŝi ne volas iri kun li.',
	'Jes, ŝi volas iri kun li.',
	'Ili volas ludi ekstere.',
	'Ili volas ludi la pianon.',
	'Ili volas ludi tenison.',
	'Ili volas ludi kun amikoj.',
	'Ĉu nun pluvas?',
	'Jes, nun pluvas.',
	'Ĉu pluvas multe?',
	'Ne, ne pluvas multe.',
	'Pluvas iomete.',
	'Ĉu neĝas nun?',
	'Jes, nun neĝas.',
	'Ne, nun ne neĝas.',
	'Ĉu nun neĝas en Ŝanhajo?',
	'Jes, en Ŝanhajo nun neĝas.',
	'Ĉu blovas nun?',
	'Jes, blovas forte.',
	'Ĉu blovas ekstere?',
	'Ne, ne blovas ekstere.',
	'Ĉu hodiaŭ estas nube?',
	'Jes, hodiaŭ estas tre nube.',
	'En la ĉielo troviĝas multaj nuboj.',
	'La ĉielo estas nuboplena.',
	'Ĉu hodiaŭ estas hele?',
	'Jes, hodiaŭ estas tre hele.',
	'La suno brilas.',
	'Hodiaŭ la vetero estas tre bona.',
	'Hieraŭ la vetero ne estis bona.',
	'Saluton, fraŭlino!',
	'Saluton, sinjoro!',
	'Mi venis de Ĉinio.',
	'Mi estas ĉina esperantisto.',
	'Mia nomo estas Petro Sun.',
	'Mia nomo estas Folia Li.',
	'Jen estas mia amiko Briko.',
	'Saluton, Briko!',
	'Li venis de Koreio.',
	'Mi ĝojas renkonti vin.',
	'Ankaŭ mi ĝojas vidi vin.',
	'Ĉu vi estas studento?',
	'Jes, mi estas studento.',
	'Ĉu vi estas studento de Zaozhuang Universitato?',
	'Jes, mi estas studento de Zaozhuang Universitato.',
	'Mia universitato estas en la urbo Zaozhuang.',
	'Ĉu via universitato estas granda?',
	'Jes, mia universitato estas granda kaj bona.',
	'Ĝis revido!',
	'Mi eklernis Esperanton antaŭ tri monatoj.',
	'Mi estas komencanto.',
	'Mi studas en la universitato Zaozhuang.',
	'Mi ŝatas kanti kaj danci.',
	'Mia hobio estas vojaĝo.',
	'Mia naskiĝloko estas Pekino.',
	'Nun mi loĝas en Zaozhuang.',
	'Mi volas fariĝi instruisto.',
	'Kio estas via profesio?',
	'Mi estas studento.',
	'Mia familio konsistas el kvin membroj.',
	'Miaj gepatroj loĝas en Ŝanhajo.',
	'Mi volas esti bona amiko kun vi.',
	'Mi havas unu fratinon.',
	'Mi havas du fratojn.',
	'Mi havas unu fratinon kaj unu fraton.',
	'(Koran) Dankon.',
	'Mi tre ĝojas renkonti vin.',
	'Mi ĝojas vidi vin.',
	'Venu al mi tuj.',
	'Venu al mia hejmo.',
	'Venu al la lernejo.',
	'Iru tien.',
	'Iru al via hejmo.',
	'Iru al la loko.',
	'Iru al via amiko.',
	'Ne tuŝu ĝin.',
	'Ne mensogu.',
	'Ne vizitu la profesoron.',
	'Ne manĝu multe.',
	'Iru kun li',
	'Mi iru kun li.',
	'Mi diru la veron.',
	'Li venu al mi morgaŭ matene.',
	'Ŝi prenu ĝin.',
	'Mi donu ĝin al ŝi.',
	'(Vi) Donu ĝin al li.',
	'Li donu ĝin al ŝi.',
	'Ŝi donu ĝin al mi.',
	'Ĉu povas okazi, ke li estas via amiko?',
	'Ĉu povas okazi, ke li ne rekonas vin?',
	'Ĉu povas okazi, ke li jam foriris?',
	'Ĉu povas okazi, ke li sola faris tion?',
	'Ĉu povas okazi, ke vi ankaŭ estis tie?',
	'Ĉu povas okazi, ke vi ŝtelis ĝin?',
	'Ĉu povas okazi, ke vi malamas lin?',
	'Ĉu povas okazi, ke vi diras tiamaniere?',
	'Ĉu povas okazi, ke ŝi estas via panjo?',
	'Ĉu povas okazi, ke ŝi ne obeas vin?',
	'Ĉu povas okazi, ke ŝi estas tiel mensogema?',
	'Ĉu povas okazi, ke ŝi havas tiel grandan filinon?',
	'Ĉu povas okazi, ke ĝi apartenas al li?',
	'Ĉu povas okazi, ke ĝi estas tiel multekosta?',
	'Ĉu povas okazi, ke ĝi estis perdita?',
	'Ĉu povas okazi, ke ĝi estas tiel malgranda?',
	'Ĉu povas okazi, ke vi forgesis tion?',
	'Ĉu povas okazi, ke ili malamas unu la alian?',
	'Ĉu povas okazi, ke la libro estas forŝirita?',
	'Ĉu povas okazi, ke la akvo estas dolĉa?',
	'Ĉu vi pensas, ke mi eraris?',
	'Ĉu vi pensas, ke tio estas vera?',
	'Ĉu vi pensas, ke morgaŭ li ne venos?',
	'Ĉu vi pensas, ke Esperanto estas facila?',
	'Ĉu li pensas, ke li povos fari ĝin?',
	'Ĉu li pensas, ke ŝi amas lin?',
	'Ĉu li pensas, ke ni ne povos fari ĝin?',
	'Ĉu li pensas, ke ankaŭ vi kune iros?',
	'Ĉu vi ne pensas, ke morgaŭ pluvos?',
	'Ĉu vi ne pensas, ke vi povas erari?',
	'Ĉu vi ne pensas, ke li povos helpi vin?',
	'Ĉu vi ne pensas, ke ŝi venkos lin?',
	'Ĉu li ne pensas, ke li devas lerni ĝin?',
	'Ĉu li ne pensas, ke ŝi jam foriris?',
	'Ĉu ŝi ne pensas, ke ĝi estas tre interesa?',
	'Ĉu ŝi ne pensas, ke ili estas niaj amikoj?',
	'Ĉu oni pensas, ke li estas malbonulo?',
	'Ĉu oni pensas, ke ni malsukcesis?',
	'Ĉu ili pensas, ke ili jam sukcesis en ĝi?',
	'Ĉu ili pensas, ke morgaŭ estas la tago?',
	'Ĉu vi scias, ke ĝi estas vera?',
	'Jes, mi scias, ke ĝi estas vera.',
	'Ĉu li scias, ke ŝi ne amas lin?',
	'Jes, li bone scias tion.',
	'Ĉu vi ne scias, ke ŝi jam foriris?',
	'Ĉu li diris, ke li lernos Esperanton?',
	'Jes, li diris, ke li lernos Esperanton.',
	'Ne, li ne diris, ke li lernos Esperanton.',
	'Ĉu ŝi diris, ke ŝiaj okuloj estas bonaj?',
	'Jes, ŝi diris, ke ŝiaj okuloj estas bonaj.',
	'Ne, ŝi ne diris, ke ŝiaj okuloj estas bonaj.',
	'Oni scias, ke ŝiaj okuloj estas bonaj.',
	'Oni diras, ke li estas bona homo.',
	'Oni diras, ke ŝi estas bela.',
	'Oni diras, ke ĝi estas multekosta.',
	'Oni diras, ke ili venos morgaŭ.',
	'Mi diris, ke mi ne scias.',
	'Ĉu vi ne aŭdis, ke mi ne scias?',
	'Ĉu vi scias, ke li ne venos?',
	'Jes, mi scias, ke li ne venos.',
	'Ĉu vi scias, kie li estas?',
	'Jes, mi scias. Li estas en la lernejo.',
	'Ĉu vi scias, kie estas la sinjoro?',
	'Jes, mi scias. Li estas en la ĉambro.',
	'Ĉu vi scias, kie estas Zaozhuang Universitato?',
	'Jes, mi scias. Ĝi estas en la urbo Zaozhuang.',
	'Ĉu vi scias, kie estas mia poŝtelefono?',
	'Jes, mi scias. Ĝi estas sub la seĝo.',
	'Ĉu li scias, kie estas via hejmo?',
	'Jes, li scias, kie estas mia hejmo.',
	'Ĉu ŝi scias, kie estas ŝia patrino?',
	'Jes, ŝi scias, kie estas ŝia patrino.',
	'Ĉu li scias, kie estas Koreio?',
	'Jes, li scias, kie estas Koreio.',
	'Ĉu ŝi scias, kie estas la bazaro?',
	'Jes, ŝi scias, kie estas la bazaro.',
	'Ĉu s-ro Liu scias, kio ĝi estas?',
	'Jes, s-ro Liu scias, kio ĝi estas.',
	'Ĉu s-ino Sun scias, kie estas la knabino?',
	'Jes, s-ino Sun scias, kie estas la knabino.',
	'Ĉu vi scias, kiel ludi la pianon?',
	'Jes, mi scias, kiel ludi ĝin.',
	'Ĉu vi scias, kiel kanti la kanton?',
	'Jes, mi scias, kiel kanti ĝin.',
	'Ĉu vi scias, kiel skribi lian nomon?',
	'Jes, mi scias, kiel skribi lian nomon.',
	'Ĉu vi scias, kiel iri al la lernejo?',
	'Jes, mi scias, kiel iri al la lernejo.',
	'Ĉu li scias, kiel fari ĝin?',
	'Ne, li ne scias, kiel fari ĝin.',
	'Ĉu ŝi scias, kiel solvi la aferon?',
	'Ne, ŝi ne scias, kiel solvi la aferon.',
	'Mi ne scias, kiel manĝi la fiŝon.',
	'Li ne scias, kiel nomi lin.',
	'Ŝi ne scias, kiel persvadi la patron.',
	'Vi ne scias, kiel konduti antaŭ li.',
	'Mi ne scias, kiel esprimi tion.',
	'Ĉu vi scias, kiel prononci ĝin?',
	'Neniu scias, kiel diri ĝin en Esperanto.',
	'Ĉiuj scias, kiel saluti en Esperanto.',
	'Ĉu vi scias, kio ĝi estas?',
	'Jes, mi scias. Ĝi estas sako.',
	'Ĉu vi scias, kiu li estas?',
	'Jes, mi scias. Li estas ŝia amiko.',
	'Ĉu vi scias, kiu estas la knabo?',
	'Jes, mi scias. Li estas ŝia frato.',
	'Ĉu vi scias, kion li legas?',
	'Jes, mi scias. Li legas ĉinan poemon.',
	'Ĉu vi scias, kion ŝi manĝas?',
	'Jes, mi scias. Ŝi manĝas picon.',
	'Ĉu vi scias, kiun li renkontis?',
	'Jes, mi scias. Li renkontis sian amikon.',
	'Ĉu vi scias, kiun ŝi amas?',
	'Jes, mi scias. Ŝi amas Petron.',
	'Ĉu li scias, kio ĝi estas?',
	'Jes, li scias, kio ĝi estas. (Ĝi estas libro.)',
	'Ĉu ŝi scias, kiu li estas?',
	'Jes, ŝi scias, kiu li estas. (Li estas s-ro Liu.)',
	'Ĉu estas bone (por mi) lerni Esperanton?',
	'Jes, estas bone (por vi) lerni Esperanton.',
	'Ĉu estas bone por ŝi iri kun li?',
	'Jes, estas bone por ŝi iri kun li.',
	'Ĉu estas necese viziti lin?',
	'Jes, estas necese viziti lin.',
	'Ĉu estas nepre necese aĉeti ĝin?',
	'Jes, estas nepre necese aĉeti ĝin.',
	'Estas malbone kanti en nokto.',
	'Estas malbone laŭte krii en klasoĉambro.',
	'Estas dezirinde tuj renkonti lin.',
	'Estas preferinde elekti ĝin.',
	'Estas bone (por vi) ne fari tion.',
	'Estas bone (por vi) ne ekiri nun.',
	'Estas bone por li ne vidi ŝin.',
	'Estas bone por ŝi ne manĝi ĝin.',
	'Ne estas bone skribi sur la tablo.',
	'Ne estas bone multe elspezi monon.',
	'Ne estas bone batali kun amikoj.',
	'Ne estas bone diri tiamaniere.',
	'Estas certe, ke li ne venos.',
	'Estas certe, ke ŝi forgesis tion.',
	'Estas certe, ke ili kaŝos ĝin.',
	'Estas certe, ke s-ro Liu edziĝos kun ŝi.',
	'Estas bone, ke vi lernas Esperanton.',
	'Estas bone, ke ili ne elektis ĝin.',
	'Estas bone, ke ili interkonsentis pri tio.',
	'Estas bone, ke la knabo resaniĝis.',
	'Estas verŝajne, ke ŝi venos morgaŭ.',
	'Estas verŝajne, ke li ne respondos al vi.',
	'Estas kompreneble, ke ili ne jesis.',
	'Estas ne kredeble, ke ŝi edziniĝis al li.',
	'Estas ne kredeble, ke li ŝtelis ĝin.',
	'Estas kredeble, ke ili mortigis lin.',
	'Estas agrable, ke vi volas iri kun mi.',
	'Estas agrable, ke li permesis tion.',
	'Estas interese, ke li trompis ŝin.',
	'Estas interese, ke li jam foriris.',
	'Estas bedaŭrinde, ke vi ne povis vidi ŝin.',
	'Estas bedaŭrinde, ke ĝi ne estas bela.',
	'Estas bedaŭrinde, ke oni jam finis tion.',
	'Ĉu hodiaŭ estas varme?',
	'Jes, hodiaŭ estas varme.',
	'Ĉu ankaŭ hieraŭ estis varme?',
	'Ne, hieraŭ ne estis varme.',
	'Ĉu hodiaŭ estas malvarme?',
	'Jes, hodiaŭ estas malvarme.',
	'Ne, hodiaŭ ne estas malvarme.',
	'Ĉu morgaŭ estos malvarme?',
	'Eble morgaŭ ankaŭ estos malvarme.',
	'Nun estas tre freŝe.',
	'Jes, estas tre freŝe.',
	'Ĉu tie estas varmete?',
	'Jes, ĉi tie estas varmete.',
	'En Zaozhuang vintre estas iom varme.',
	'Ĉu en via hejmloko vintre estas varme?',
	'Jes, varme.',
	'Kiel estas la vetero en la somero?',
	'En la somero estas tre tre varme.',
	'Tie en printempo kaj aŭtuno estas freŝe.',
	'Ankaŭ ĉi tie estas freŝe tiam.',
	'Hieraŭ estis tro varme, ĉu ne?',
	'Jes, hieraŭ estis varmege.',
	'Kiel povas okazi, ke vi malsukcesis?',
	'Kiel povas okazi, ke vi perdis ĝin?',
	'Kiel povas okazi, ke vi ne scias tion?',
	'Kiel povas okazi, ke vi amas ŝin?',
	'Kiel povas okazi, ke li ne vidis ĝin?',
	'Kiel povas okazi, ke li ne venos morgaŭ?',
	'Kiel povas okazi, ke li sola manĝis la tuton?',
	'Kiel povas okazi, ke lia patro ankoraŭ vivas?',
	'Kiel povas okazi, ke ŝi ne volas ĝin?',
	'Kiel povas okazi, ke ŝi ankoraŭ ne scias?',
	'Kiel povas okazi, ke ŝi forgesis ĝin?',
	'Kiel povas okazi, ke ŝi retrovis ĝin tiel faicle?',
	'Kiel povas okazi, ke mi ne scias ĝin?',
	'Kiel povas okazi, ke mi vidas vin du fojojn en unu tago?',
	'Kiel povas okazi, ke mi ne memoras ĝin?',
	'Kiel povas okazi, ke mi agis tiel stulte?',
	'Kiel povas okazi, ke ili ne venis hodiaŭ?',
	'Kiel povas okazi, ke ŝi volas iri sola?',
	'Kiel povas okazi, ke vi ne diris tion al li?',
	'Kiel povas okazi, ke ili jam revenis?',
	'Kiel vi pensas pri tio?',
	'Mi pensas, ke tio estas bona.',
	'Mi opinias, ke tio estas malbona.',
	'Kiel vi venis al Pekino?',
	'Mi venis per trajno.',
	'Kiel vi agis?',
	'Mi agis sincere.',
	'Mi agis laŭ mia konscienco.',
	'Kiel multe vi manĝis?',
	'Mi manĝis tre multe.',
	'Kiel vi sukcesis?',
	'Mi sukcesis per honesteco.',
	'Kiel vi iros al Koreio?',
	'Mi flugos per aviadilo.',
	'Kiel li venis ĉi tien?',
	'Li venis ĉi tien per trajno.',
	'Kiel bela ŝi estas!',
	'Jes, ŝi estas tre bela.',
	'Kiel multe pluvas hodiaŭ!',
	'Jes, hodiaŭ pluvas tre multe.',
	'Kiel bele li kantas!',
	'Jes, li kantas tre bele.',
	'Kiun daton ni havas hodiaŭ?',
	'Hodiaŭ estas la deka de oktobro.',
	'Hodiaŭ estas la kvina de aprilo.',
	'Kiu dato estas morgaŭ?',
	'Morgaŭ estas la dek-unu-a de majo.',
	'Morgaŭ estas la oka de septembro.',
	'Kiun daton ni havis hieraŭ?',
	'Hieraŭ estis la sepa de decembro.',
	'Hieraŭ estis la dua de januaro.',
	'Kiu tago (de la semajno) estas hodiaŭ?',
	'Hodiaŭ estas dimanĉo.',
	'Kiam estas via naskotago?',
	'Mia naskotago estas la 1-a de marto.',
	'En kiu dato okazis la akcidento?',
	'La akcidento okazis en la tria de junio.',
	'En kiu dato okazos lia edziĝoceremonio?',
	'Ĝi okazos en la naŭa de septembro.',
	'Li demandis, ĉu mi scias ĝin.',
	'Li demandis, ĉu vi ankaŭ scias ĝin.',
	'Li demandis, ĉu ĝi estas vera.',
	'Li demandis, ĉu ili permesos ĝin.',
	'Ŝi demandis, ĉu vi ankaŭ venos.',
	'Ŝi demandis, ĉu vi amas ŝin.',
	'Ŝi demandis, ĉu ili povas fari tion.',
	'Ŝi demandis, ĉu vi povas helpi ŝin.',
	'Vi demandas, ĉu mi scias ĝin.',
	'Vi demandas, ĉu li estas mia frato.',
	'Vi demandas, ĉu mia frato estas bona.',
	'Vi demandas, ĉu ŝi vere amas min.',
	'Mi demandis, ĉu li manĝis jam.',
	'Mi demandis, ĉu tio estas vero.',
	'Mi demandis, ĉu ili ankoraŭ ne venis.',
	'Mi demandis, ĉu ŝi estas via amikino.',
	'Demandu ŝin, ĉu ŝi scias la veron.',
	'Demandu lin, ĉu li amas ŝin.',
	'Demandu vian amikon, ĉu li volas ĝin.',
	'Demandu la panjon, ĉu ŝi vidos lin.',
	'Li mensogas, kvazaŭ ĝi estus vero.',
	'Li mensogas, kvazaŭ li ne erarus.',
	'Li mensogas, kvazaŭ ŝi amus lin.',
	'Li mensogas, kvazaŭ lia patro permesus tion.',
	'Li diras, kvazaŭ li scius ĉion.',
	'Li agas, kvazaŭ li ne scius tion.',
	'Li fanfaronas, kvazaŭ li estus tre riĉa.',
	'Li proponas, kvazaŭ ĝi estus tre utila.',
	'(Vi) Ne diru, kvazaŭ vi scius ĉion.',
	'Ne fanfaronu, kvazaŭ vi sola farus ĝin.',
	'Ne mensogu, kvazaŭ ŝi amus vin.',
	'Ne malĝoju, kvazaŭ la mondo tuj pereus.',
	'Ne malĝoju, kvazaŭ ili ĉiuj malamus vin.',
	'Ne malĝoju, kvazaŭ vi estus orfo.',
	'Ne troigu, kvazaŭ ĝi estus la plej grava.',
	'Ne troigu, kvazaŭ vi perdus ĉion.',
	'Li ofte diras, kvazaŭ liaj vortoj estus veraj.',
	'Ili ĉiam krias, kvazaŭ ili ĉiam venkus.',
	'Mi ne diras, kvazaŭ mi scius ĉion pri tio.',
	'Mi ne volas diri, kvazaŭ mi tute ne erarus.',
	'Li venu anstataŭ vi.',
	'Li iru kun vi.',
	'Li sidu tie apud vi.',
	'Li helpu ŝin.',
	'Ŝi vizitu la sinjoron morgaŭ matene.',
	'Ŝi montru sian sincerecon.',
	'Ŝi ne malhelpu la aferon.',
	'Ŝi ne parolu mensoge.',
	'Ili kunlaboru en la afero.',
	'Ili vekiĝu frue morgaŭ matene.',
	'Ili diru la veron.',
	'Ili mem venu al mi.',
	'Ĉu li iru al vi anstataŭ mi?',
	'Jes, li venu al mi anstataŭ vi.',
	'Ĉu ŝi laboru por vi morgaŭ?',
	'Jes, ŝi laboru por mi morgaŭ.',
	'Ĉu ili helpu vin?',
	'Jes, ili helpu min.',
	'Ĉu la knabo vizitu vin?',
	'Jes, li vizitu min.',
	'Ĉu mia frato anstataŭi vin?',
	'Jes, li anstataŭi min.',
	'Ĉu ili ne plu venu al vi?',
	'Jes, ili daŭre venu al mi.',
	'Mi bedaŭras, ke vi ne sukcesis.',
	'Mi bedaŭras, ke ili ne venis.',
	'Mi bedaŭras, ke ŝi estas tre malsana.',
	'Mi bedaŭras, ke mi ne povas helpi vin.',
	'Li bedaŭris, ke vi ne povis kunveni.',
	'Li bedaŭris, ke ŝi ne kredas lin.',
	'Li bedaŭris, ke mi ne estis kun li.',
	'Li bedaŭris, ke ĝi malaperis.',
	'Ĉu vi bedaŭras, ke li ne venis?',
	'Jes, mi bedaŭras, ke li ne venis.',
	'Ĉu vi bedaŭras, ke vi perdis ĝin?',
	'Jes, mi tre bedaŭras, ke mi perdis ĝin.',
	'Ĉu li bedaŭris, ke ŝi ne venis?',
	'Jes, li tre bedaŭris, ke ŝi ne venis.',
	'Ĉu ili bedaŭris, ke ni jam foriris?',
	'Jes, ili tre bedaŭris, ke vi jam foriris.',
	'Mi ne bedaŭras, ke tio nuliĝis.',
	'Li ne bedaŭras, ke tio perdiĝis.',
	'Ŝi ne bedaŭras, ke ili ne amas ŝin.',
	'Ili ne bedaŭras, ke mi ne helpis ilin.',
	'Mi deziras, ke vi sukcesu.',
	'Mi deziras, ke vi bone komprenu tion.',
	'Mi deziras, ke vi tuj resaniĝu.',
	'Mi deziras, ke vi ankaŭ venu morgaŭ.',
	'Mi deziras, ke li revenu plej frue.',
	'Mi deziras, ke li povu akiri ĝin.',
	'Mi deziras, ke li ne eksciu tion.',
	'Mi deziras, ke li ne vidu ĝin.',
	'Mi deziras, ke mi povu renkonti ŝin.',
	'Mi deziras, ke mi gastigu vin baldaŭ.',
	'Mi deziras, ke mi povu helpi vin.',
	'Mi deziras, ke mi retrovu ĝin tre baldaŭ.',
	'Ĉu vi deziras, ke mi ne venu al vi?',
	'Ĉu vi deziras, ke li komprenu vin?',
	'Ĉu vi deziras, ke ŝi estu kun vi?',
	'Ĉu vi deziras, ke ili ne rimarku ĝin?',
	'Li deziras, ke mi helpu lin.',
	'Ŝi deziras, ke mi ne helpu lin.',
	'Ili deziras, ke neniu helpu lin.',
	'Ĉu li deziras, ke ŝi ne manĝu ĝin?',
	'Ĉu ili deziras, ke li ne povu venki vin?',
	'Mi diris, ke ĝi estas bona.',
	'Mi diris, ke li estas bonkora.',
	'Mi diris, ke ŝi estas afabla.',
	'Mi diris, ke ili estas bonaj amikoj.',
	'Vi diris, ke vi estas okupita.',
	'Vi diris, ke li estas malsana.',
	'Vi diris, ke ŝi estas bela.',
	'Vi diris, ke ili estas viaj amikoj.',
	'Li diris, ke li estas malsana.',
	'Li diris, ke lia frato estas malsana.',
	'Li diris, ke ĝi estas bona.',
	'Li diris, ke ili estas bonaj.',
	'Ŝi diris, ke mi estas malbona homo.',
	'Ŝi diris, ke li estas bona amiko.',
	'Ŝi diris, ke ĝi estas bela.',
	'Ŝi diris, ke ŝi nun estas tre kolera.',
	'Ĉu vi diris, ke ĝi estas bona?',
	'Ĉu vi diris, ke ŝi estas via amikino?',
	'Ĉu li diris, ke li loĝas en Pekino?',
	'Ĉu ŝi diris, ke hodiaŭ estas ŝia naskotago?',
	'Mi dubas, ĉu ŝi estas feliĉa.',
	'Mi dubas, ĉu ŝi jam foriris.',
	'Mi dubas, ĉu ŝi vere alvenis.',
	'Mi dubas, ĉu ŝi jam endormiĝis.',
	'Mi dubas, ĉu vi diras la veron.',
	'Mi dubas, ĉu li vere faris tion.',
	'Mi dubas, ĉu ili jam scias ĝin.',
	'Mi dubas, ĉu vi estas vere malsana.',
	'Li dubas, ĉu mi donos ĝin al li.',
	'Li dudas, ĉu vi venos al li.',
	'Ŝi dubas, ĉu vi amas ŝin.',
	'Ili dubas, ĉu ni parolas en Esperanto.',
	'Neniu dubas, ke ĝi estas bona.',
	'Neniu dubas, ke ŝi jam diris tion al li.',
	'Oni ne dubas, ke vi estas bona homo.',
	'Oni ne dubas, ke li estas forta.',
	'Li ne dubas, ke Esperanto estas facila.',
	'Li ne dubas, ke ŝi venos morgaŭ.',
	'Mi ne dubas, ke vi sukcesos en la afero.',
	'Mi ne dubas, ke li helpos ŝin.',
	'Mi esperas, ke vi sukcesos.',
	'Mi esperas, ke vi venos morgaŭ.',
	'Mi esperas, ke vi renkontos ŝin.',
	'Mi esperas, ke vi kunsidos kun ni.',
	'Mi esperas, ke li povos solvi ĝin.',
	'Mi esperas, ke li ankaŭ venos kun vi.',
	'Mi esperas, ke li komprenos tion.',
	'Mi esperas, ke li ne diros ĝin al ĉiuj.',
	'Li esperas, ke ŝi kantos sukcese.',
	'Li esperas, ke ŝi ne ekscios ĝin.',
	'Li esperas, ke ŝi tuj endormiĝos.',
	'Li esperas, ke ŝi bone regalos vin.',
	'Ĉu vi esperas, ke mi diros ĝin al li?',
	'Ĉu vi esperas, ke ŝi mem venos al vi?',
	'Ĉu li esperas, ke mi vizitos lin?',
	'Ĉu li esperas, ke ili ne faros tion?',
	'Ĉu ŝi esperas, ke vi forgesos ŝin?',
	'Ĉu ŝi esperas, ke oni ne memoros ŝin?',
	'Ĉu ili esperas, ke ĝi estos malvera?',
	'Ĉu ili esperas, ke la knabino ne aperos?',
	'Mi ĝojas, ke vi venis.',
	'Mi ĝojas, ke vi sukcesis.',
	'Mi ĝojas, ke vi invitis min.',
	'Mi ĝojas, ke vi diris al mi la veron.',
	'Mi ĝojas, ke ĝi ne estas multekosta.',
	'Mi ĝojas, ke ili konsentis pri tio.',
	'Mi ĝojas, ke via patro pardonis min.',
	'Mi ĝojas, ke la vetero estas tre bona.',
	'Ĉu vi ĝojas, ke vi sukcesis je tio?',
	'Ĉu vi ĝojas, ke ili helpis vin?',
	'Ĉu vi ĝojas, ke oni samopinias kun vi?',
	'Ĉu vi ĝojas, ke ŝi silentas pri tio?',
	'Mi ne ĝojas, ke mi ne povis vidi ŝin.',
	'Mi ne ĝojas, ke ĝi rompiĝis.',
	'Ili ne ĝojas, ke mi forlasis ilin.',
	'Ŝi ne ĝojas, ke li trompis ŝin.',
	'Ĉu vi ne ĝojas, ke mi ne diris ĝin al vi?',
	'Ĉu vi ne ĝojas, ke la hundo mortis?',
	'Ĉu li ne ĝojas, ke ili malhelpas lin?',
	'Ĉu ŝi ne ĝojas, ke oni ne amas ŝin?',
	'Ĉu ili ne ĝojas, ke la novaĵo estas erara?',
	'Mi ne komprenas, kial li ploras.',
	'Mi ne komprenas, kial ŝi krias tiel laŭte.',
	'Mi ne komprenas, kial ili batalas inter si.',
	'Mi ne komprenas, kial vi koleras.',
	'Mi ne komprenas, kial oni malamas lin.',
	'Mi ne komprenas, kial ĝi estas tiel multekosta.',
	'Mi ne komprenas, kial vi elektis ĝin.',
	'Mi ne komprenas, kial mi devas helpi vin.',
	'Mi ne komprenas, kial la mondo estas tiel.',
	'Mi ne komprenas, kial ni devas fari tion.',
	'Mi ne komprenas, kial la katoj malamas musojn.',
	'Mi ne komprenas, kial la bebo ploras.',
	'Vi ne komprenas, kial mi diras tiel.',
	'Vi ne komprenas, kial ŝi ne venis kune.',
	'Li ne komprenas, kial vi agas tiel al li.',
	'Ŝi ne komprenas, kial li ne respondis al ŝi.',
	'Ĉu vi komprenas, kial oni ŝatas ĝin?',
	'Ĉu vi komprenas, kial ŝi nomas lin patro?',
	'Ĉu vi komprenas, kial mi ne iris al vi?',
	'Ĉu vi komprenas, kial li estas tiel aroganta?',
	'Mi ne scias, kial li koleras.',
	'Mi ne scias, kial li ne venis.',
	'Mi ne scias, kial li manĝis ĝin.',
	'Mi ne scias, kial li batis lin.',
	'Mi ne scias, kial ŝi ploras.',
	'Mi ne scias, kial ŝi forkuris.',
	'Mi ne scias, kial ŝi iris al li.',
	'Mi ne scias, kial ŝi ankoraŭ ne venas.',
	'Vi ne scias, kial mi ne diras tion al vi.',
	'Vi ne scias, kial ŝi venis al mi.',
	'Vi ne scias, kial li vokas ŝin.',
	'Vi ne scias, kial ili kune laboras.',
	'Li ne scias, kial ŝi amas lin.',
	'Li ne scias, kial li perdis ŝin.',
	'Li ne scias, kial ili ne ŝatas lin.',
	'Li ne scias, kial la amiko malaperis.',
	'Ŝi ne scias, kial ĝi estas tia.',
	'Ŝi ne scias, kial ili estas tiel feliĉaj.',
	'Ili ne scias, kial la tero estas ronda.',
	'Ili ne scias, kial la suno brilas.',
	'Mi pensas, ke li estas ĝusta.',
	'Mi pensas, ke li diris la veron.',
	'Mi pensas, ke li ne venos.',
	'Mi pensas, ke li estas ŝia patro.',
	'Mi pensas, ke ĝi ne estas lia.',
	'Mi pensas, ke ĝi estas tre grava.',
	'Mi pensas, ke ŝi eraris.',
	'Mi pensas, ke ŝi amas lin.',
	'Mi pensas, ke morgaŭ pluvos.',
	'Mi pensas, ke iam venos la tempo.',
	'Mi pensas, ke hieraŭ li ne venis.',
	'Mi pensas, ke hodiaŭ estas la tago.',
	'Li pensas, ke mi ne kredas lin.',
	'Li pensas, ke ĝi estas lia libro.',
	'Li pensas, ke vi malamas lin.',
	'Li pensas, ke vi ne estas afabla al li.',
	'Mi pensis, ke li prenis ĝin.',
	'Li pensis, ke mi ne trovis ĝin.',
	'Ŝi pensis, ke li trompas ŝin.',
	'Ili pensis, ke ni ne ŝatas ilin.',
	'Mi promesas tuj viziti vin.',
	'Mi promesas renkonti lin morgaŭ.',
	'Mi promesas ne fari tion.',
	'Mi promesas ne doni ĝin al ŝi.',
	'Mi promesas nepre reveni.',
	'Mi promesas lerni pli diligente.',
	'Mi promesas ne mensogi plu.',
	'Mi promesas protekti ŝin.',
	'Mi promesas obei la regulon.',
	'MI promesas respekti la regulon.',
	'Mi promesas vekiĝi frumatene.',
	'Mi promesas enlitiĝi frue.',
	'Li promesis doni ĝin al vi.',
	'Ŝi promesis aĉeti ĝin al vi.',
	'Vi promesis kuiri ĝin al mi.',
	'Li promesis telefoni al mi morgaŭ.',
	'Vi promesis doni ĝin al mi.',
	'Vi promesis iri tien kun mi.',
	'Li promesis ne bati la fraton.',
	'Ŝi promesis reveni morgaŭ.',
	'Permesu, ke mi vidu ĝin.',
	'Permesu, ke mi faru tion.',
	'Permesu, ke mi vizitu ŝin.',
	'Permesu, ke mi foriru nun.',
	'Permesu lin enveni en la ĉambron.',
	'Permesu lin dormi en la ĉambro.',
	'Permesu lin manĝi kun ili.',
	'Permesu lin edziĝi kun ŝi.',
	'Permesu ŝin kanti kun ili.',
	'Permesu ŝin ludi kun la amikoj.',
	'Permesu ŝin ripozi sola.',
	'Permesu ŝin preni ĝin.',
	'Mi permesas vin preni (, ke vi prenu) ĝin.',
	'Mi permesas vin kisi (, ke vi kisu) min.',
	'Mi permesas vin foriri (, ke vi foriru) nun.',
	'Mi permesas vin fari (, ke vi faru) tion.',
	'Mi permesis ilin sekvi min.',
	'Mi permesos neniun iri kun mi.',
	'Mi ne permesos vin fari tiel.',
	'Petu lin, ke li helpu min.',
	'Petu lin, ke li ne faru tion.',
	'Petu lin, ke li ne plu mensogu.',
	'Petu lin, ke li ne manĝu ĝin.',
	'Petu ŝin, ke ŝi laboru pli diligente.',
	'Petu ŝin, ke ŝi kuru rapide.',
	'Petu ŝin, ke ŝi akceptu mian donacon.',
	'Petu ŝin, ke ŝi permesu ĝin al mi.',
	'Povas esti, ke tuj pluvos.',
	'Povas esti, ke li ne venos.',
	'Povas esti, ke li malsukcesos en la afero.',
	'Povas esti, ke li alvenos baldaŭ.',
	'Povas esti, ke mi ne plu laboros tie.',
	'Povas esti, ke mi ne povos plu vidi vin.',
	'Povas esti, ke vi devos mem fari tion.',
	'Povas esti, ke vi miskomprenis ŝin.',
	'Povas esti, ke ŝi jam revenis hejmen.',
	'Povas esti, ke ŝi tute ne helpos vin.',
	'Povas esti, ke ili estis tro liberaj.',
	'Povas esti, ke ili neniom zorgis pri li.',
	'Ĉu povas esti, ke vi tiel rapide foruzis ĝin?',
	'Ĉu povas esti, ke ni devas disiĝi?',
	'Ĉu povas esti, ke li ne vidis ĝin?',
	'Ĉu povas esti, ke vi ne venos?',
	'Ĉu povas esti, ke ŝi eraris je tio?',
	'Ĉu povas esti, ke li ne scias ĝin?',
	'Ĉu povas esti, ke vi ne memoras tion?',
	'Ne povas esti, ke ĝi malaperis per si mem?',
	'Ne povas esti, ke ĝi ankoraŭ ne solviĝis?',
	'Ne povas esti, ke li malamas ŝin?',
	'Ne povas esti, ke la knabo batis lin?',
	'Ne povas esti, ke li forgesis vin.',
	'Ne povas esti, ke vi perdis la tutan monon.',
	'Ne povas esti, ke mi devas forlasi vin.',
	'Ne povas esti, ke s-ro Liu ne volas helpi vin.',
	'Ŝajnas, ke vi estas malsana.',
	'Ŝajnas, ke vi estas tre ĝoja.',
	'Ŝajnas, ke vi malsukcesis en la ekzameno.',
	'Ŝajnas, ke vi perdis ŝin.',
	'Ŝajnas, ke li estas tre stulta.',
	'Ŝajnas, ke li estas ŝia amato.',
	'Ŝajnas, ke li gajnis multan monon.',
	'Ŝajnas, ke li ne konsentas pri tio.',
	'Ŝajnas, ke ŝi mensogas.',
	'Ŝajnas, ke ŝi estas malfeliĉa.',
	'Ŝajnas, ke ŝi ne bone dormis.',
	'Ŝajnas, ke ŝi estas tre kolera.',
	'Ĉu ŝajnas, ke ili jam forlasis?',
	'Ĉu ŝajnas, ke ili perdis ĉion?',
	'Ĉu ŝajnas, ke ili ne povos venki lin?',
	'Ĉu ŝajnas, ke ili jam malesperiĝis?',
	'Ĉu ŝajnas, ke mi trompas vin?',
	'Ĉu ŝajnas, ke mi ne diras la veron?',
	'Ĉu ŝajnas, ke mi dubas pri tio?',
	'Ĉu ŝajnas, ke mi malsukcesis?',
	'Se mi estus vi, mi ne farus tiel.',
	'Se mi estus vi, mi ne irus tien.',
	'Se mi estus vi, mi akceptus lian proponon.',
	'Se mi estus vi, mi dirus la veron.',
	'Se vi estus mi, ĉu vi farus tiel?',
	'Se vi estus mi, kiel vi farus?',
	'Se vi estus mi, ĉu vi ne farus tiel?',
	'Se vi estus mi, vi certe sukcesus.',
	'Se li estus riĉa, li donus al vi multan monon.',
	'Se li estus sana, li volus vojaĝi kun ni.',
	'Se ŝi estus lia edzino, ŝi ne dirus tiel.',
	'Se ŝi estus mia amiko, ŝi nepre helpus vin.',
	'Ĉu vi pardonus lin, se li venus al vi?',
	'Ĉu vi manĝus ĝin, se ĝi estus saniga?',
	'Ĉu li venus, se ŝi venus?',
	'Ĉu ŝi ankaŭ irus, se li volas iri tien?',
	'Mi ne vizitus lin, se li ne volus.',
	'Mi ne donus ĝin al li, se li ne volus ĝin.',
	'Li ne akceptus ĝin, se ĝi ne estus vera.',
	'Ŝi ne estus feliĉa, se li ne akceptus ĝin.',
	'Se vi donos ĝin al mi, mi ĝojos.',
	'Se vi iros, ankaŭ mi iros.',
	'Se vi renkontos ŝin, ŝi tre ĝojos.',
	'Se vi legos la libron, vi povos ekscii ĝin.',
	'Se mi donos ĝin al vi, kion vi donos al mi?',
	'Se mi ne scias ĝin, mi ne diras tion.',
	'Se vi diras, mi kredas tion.',
	'Se ŝi diras la veron, mi akceptos ŝin.',
	'Se morgaŭ venos li, ĉu vi ankaŭ venos?',
	'Se morgaŭ estos varme, mi ne eliros.',
	'Se li estas la sinjoro, mi renkontos lin.',
	'Se ili ne scias tion, ne diru al ili pri ĝi.',
	'Se ĝi ne estas via, vi ne prenu ĝin.',
	'Se ŝi ne estas fidela, mi ne vidos ŝin.',
	'Se la afero estas tiel, mi devas fini ĝin.',
	'Se vi estas tiel okupita, ne venu morgaŭ.',
	'Se Esperanto estas facila, mi lernos ĝin.',
	'Se Esperanto estas malfacila, ĉiuj lingvoj estas malfacilaj.',
	'Se vi lernos Esperanton, ĝi ŝanĝos vian vivon.',
	'Se vi bone parolas en Esperanto, vi havos multajn amikojn en la mondo.',
	'Nun ni vivas en la mondo de artefarita inteligento.',
	'Jes, vere.',
	'Kaj la mondo ĉiutage ŝanĝiĝas tre multe.',
	'Sen nia konscio jam uziĝas la artefarita inteligento en diversaj kampoj.',
	'Jes, eĉ en niaj hejmoj ĝi uziĝas multe.',
	'AI(Artefarita Inteligento) estas utiligata en saĝtelefono, roboto, interreto, aŭto, ktp.',
	'Per AI ni povas facile traduki lingvojn.',
	'En interreto ni povas facile kaj rapide uzi la maŝinan tradukon.',
	'Ankaŭ Esperanto estas maŝine tradukata en Guglo.',
	'Vi povas viziti la retejon',
	'AI povas rekte interparoli kun homoj en homaj lingvoj.',
	'Oni timas, ĉu AI fariĝos granda minaco al homoj.',
	'Ni devas bone regi la progreson de AI.',
	'Laŭ la sinteno kaj volo de homaro ĝi povas direktiĝi al bono aŭ malbono.',
	'AI estas maŝino kaj sistemo.',
	'Ĝi ne estas homo.',
	'Sed ĝi povas interkomuniki kun homoj.',
	'Iam en la estonteco ĝi povos venki homojn.',
	'Kion ni faru rilate al ĝi?',
	'Bonvenon.',
	'Kiel mi helpu vin, sinjoro?',
	'Mi volas fari bankkonton.',
	'Kie mi povas fari ĝin?',
	'Tie ĉe la giĉeto tri(3) vi povas fari ĝin.',
	'Koran dankon!',
	'Bonvole enskribu informojn en la dokumento.',
	'Jen vi subskribu, mi petas.',
	'Ĉu vi havas vian stampon?',
	'Mi volas uzi mian subskribon.',
	'Ĉu vi volas uzi interretan bankon?',
	'Jen vi premu la sekretajn numerojn.',
	'Ĉu vi volas fari ankaŭ bankkarton?',
	'Mi volas fari ankaŭ kreditkarton.',
	'Mi volas deponi monon.',
	'Mi havas ĉekon.',
	'Mi volas aĉeti dolarojn kaj eŭrojn.',
	'Kia estas hodiaŭa interŝanĝa kurzo?',
	'Mi volas kontantigi ĉekon.',
	'Tie troviĝas kontantmaŝino.',
	'Multaj homoj atendas en longa vico.',
	'Mi volas eltiri monon el la kontantmaŝino.',
	'Mi perdis mian karton.',
	'Mi volas ĝiri monon al mia amiko.',
	'Al biblioteko.',
	'Kio? Mirinde.',
	'Por mi estas la unua fojo vidi vin al biblioteko.',
	'Ankaŭ por mi estas la unua fojo renkonti vin survoje al biblioteko.',
	'Ĉu vi iras studi por la ekzameno?',
	'Ne. Mi iras por serĉi artikolojn.',
	'Nuntempe ĉu vi preparas disertacion?',
	'Ĉu oni povas prunti librojn ĉe la biblioteko?',
	'Jes, kompreneble. Maksimume du librojn.',
	'Dum kiom da tagoj oni povas prunti?',
	'Unu semajnon.',
	'Mi pruntu du librojn pri lingvistiko.',
	'Grandaj legoĉambroj estas ĉe la dua kaj tria etaĝoj.',
	'Ĉe la unua etaĝo estas la ĉambro de periodaĵoj kaj referaĵoj.',
	'Je kioma horo oni fermas la bibliotekon?',
	'Je la deka nokte.',
	'Fumi kaj babili estas malpermesite en la legoĉambroj.',
	'Troviĝas aparta fumejo ekster la legoĉambroj.',
	'Multaj studentoj diligente studas en la biblioteko.',
	'Jes, nuntempe oni havas ekzamenojn.',
	'Ĉu oni povas manĝi manĝaĵojn en la biblioteko?',
	'Ne, oni ne povas manĝi.',
	'Tie venas mia kofro.',
	'Finfine venis mia vico.',
	'Bonvolu malfermi la kofron.',
	'Libroj kaj vestoj estas en la kofro.',
	'Ĉu vi ne havas multekostan aferon registrendan?',
	'Jen, fotilo.',
	'Bonvolu. Ĝin vi ne bezonas registri.',
	'Jen, kio estas la medikamento?',
	'Mia celo de la vojaĝo estas la partopreno en la kongreso de Esperanto.',
	'Kiom da tagoj vi restos?',
	'Mi havas vizon por dek kvin tagoj.',
	'Bone. Dankon.',
	'La vico estas por fremdlandanoj. Ni iru al tiu vico.',
	'Ĉu vi montrus al mi vian pasporton, sinjoro.',
	'Jen estas mia pasporto, kaj en ĝi troviĝas vizo.',
	'La flughaveno estas tre granda, kaj la oficistoj en la doganejo estas tre afablaj.',
	'Hodiaŭ venos mia amiko de Francio.',
	'Ĉu esperantisto?',
	'Jes. Li tre bone parolas en Esperanto.',
	'Li alvenos ĉe la flughaveno je la dek-unua.',
	'Oni bezonas ĉirkaŭ unu horon por trapasi doganejon.',
	'Ĉu tiel longe?',
	'Ĉinaj doganistoj tro detale kontrolas.',
	'Elirejo estas ĉe la unua etaĝo, kaj enirejo estas ĉe la dua.',
	'Ha, tie li elvenas.',
	'He Karlo! Jen, ĉi tie.',
	'Saluton, Karlo!',
	'Ĉu la vojaĝo estis agrabla?',
	'Jes, tre agrabla. Ĉu vi atendis longe?',
	'Ne tiel longe. Ĉirkaŭ dek minutojn.',
	'Mi forgesis, kie mi metis mian pasporton, kaj tial...',
	'Ĉu vi trovis ĝin?',
	'Jes, mi trovis ĝin en libro.',
	'Saluton, sinjoro Tigro.',
	'Saluton, sinjoro Karlo. Mi ĝojas vidi vin.',
	'Nu, unue ĉu ni iru al mia hejmo?',
	'Pakaĵoj estas en la kofro de la aŭto.',
	'Mi deziras unu ĉambron kun du litoj.',
	'Jen bonvolu enskribi en registrolibro.',
	'La ĉambro tri nul naŭ sur tria etaĝo.',
	'Bonvolu uzi la lifton.',
	'Jen estas la ŝlosilo.',
	'Kiom da noktoj vi restos?',
	'Du noktojn.',
	'Se vi bezonas ion, bonvolu telefoni al la ĉambroservejo.',
	'Sur kioma etaĝo estas la noktoklubo?',
	'Sur la trideka etaĝo, kaj kafejo estas ĉe la unua subtera etaĝo.',
	'Sur kioma etaĝo estas la bufedejo?',
	'Ĝi estas sur la dua etaĝo.',
	'Ĝi estas folklora muzeo.',
	'Unue ĉu ni pririgardu ekde la unua etaĝo?',
	'Ĉu ĉiuj ekspoziciaĵoj estas originalaj?',
	'Jes, ĉiuj estas elfositaj originaloj. Ili ne estas imitaĵoj.',
	'Mi miras, ke tiam la homoj povis fari ĉi tiajn ŝtonajn tranĉilojn kaj hakilojn.',
	'En kiu tempo estis faritaj ĉi tiuj ceramikaĵoj?',
	'Ili estis faritaj en la tempo de la regno Qin.',
	'Por kio oni uzis ĝin?',
	'Ĝi estas tuĉoŝtono, kiun oni uzas, kiam oni produktas tuĉolikvaĵon el tuĉobastoneto.',
	'Kiel oni uzas ĝin?',
	'Oni enverŝas gutojn da akvo en ĝin, kaj disfrotas la tuĉobastoneton sur ĝin, kaj do oni povas havi tuĉolikvaĵon.',
	'Oni uzas ĝin ĉefe por penika skribado, ĉu ne?',
	'Ĉu ĝi estas reĝa krono?',
	'Jes, ĝi estas farita entute el oro kaj gemoj.',
	'Ĉu la humideco kaj temperaturo estas regulaj en la ĉambro?',
	'Jes, en muzeo tio estas tre grava afero.',
	'Ĉi tiuj estas iloj necesaj por terkultura vivo.',
	'Mi iras al mia laborejo.',
	'Mi devas atingi ĝin ĝis la oka matene.',
	'Mi laboras 8 horojn en unu tago.',
	'Mi finas la laboron je la kvina posttagmeze.',
	'Post la laboro mi ekzerciĝas ĉe gimnastikejo.',
	'En la oficejo mi preskaŭ ĉiam laboras antaŭ komputilo.',
	'Tutan tagon mi uzas komputilon.',
	'En tagmezo mi ripozas dum unu horo.',
	'En mia oficejo kune laboras entute dek du homoj.',
	'Mia tablo estas apud fenestro.',
	'La pejzaĝo trans la fenestro estas tre bela.',
	'Hodiaŭ mia amiko vizitos min al la oficejo.',
	'Mia laboro estas tradukado inter Esperanto kaj la ĉina.',
	'Mi speciale lernis Esperantan tradukon en universitato.',
	'Mia fako estis la internacia lingvo, Esperanto.',
	'Mia salajro estas sufiĉa por mia vivo.',
	'Mi estas kontenta je mia laboro.',
	'Venis mia amiko.',
	'Bonan tagon! Ĉu vi ne estas okupita?',
	'Ne, mi ne estas tiel okupita.',
	'Ni kafumu ekstere ĉe la ripozejo.',
	'Nu, mi revenu. Bonan laboron, amiko!',
	'Kien iras la vagonaro(trajno)?',
	'Mi volas iri al Taian.',
	'Kie oni aĉetas bileton?',
	'De kiam oni eniras en la trajnon?',
	'Kie estas hortabelo?',
	'Demandu ĉe la informejo.',
	'Tie sur la muro troviĝas granda hortabelo.',
	'Ni tuj devas aĉeti bileton.',
	'Ni iru al la enirejo.',
	'En Eŭropo ne ekzistas biletokontrolejo.',
	'En la trajno de tempo al tempo la kontrolistoj kontrolas bileton.',
	'Ekiras la trajno al Pekino.',
	'Elvenas multaj pasaĝeroj.',
	'Je kioma horo la trajo atingas Pekinon?',
	'Eble je la tria kaj duono posttagmeze.',
	'Ĉu la trajno estas homplena?',
	'Eble ne.',
	'Hodiaŭ ne troviĝas multaj pasaĝeroj.',
	'Ĉu la trajno estas ekspresa trajno?',
	'Jes, ĝi estas.',
	'Kiom estas la rapideco de la trajno?',
	'Ĝia meza rapideco estas po cent tridek kilometroj hore.',
	'Bonan vojaĝon. Bonan ŝancon.',
	'Ĉu vi volas aĉeti ŝuojn?',
	'Kiaj ŝuoj taŭgas por somero?',
	'Bonvolu provi ĉi tiujn sandalojn.',
	'La kalkanumo estas tro alta.',
	'Ne estas bone porti tro altajn ŝuojn.',
	'Ĉu ne estas malpli alta?',
	'Jen estas, sed mi timas, ĉu la koloro ne plaĉus al vi.',
	'Jes, bone.',
	'Mi volas aĉeti sportoŝuojn(tolŝuojn) kaj botojn.',
	'Lastatempe sportoŝuoj(tolŝuoj) estas pli multekostaj ol ledŝuoj.',
	'Jes, kaj la sportoŝuoj estas tre popularaj.',
	'Ankaŭ mi ofte portas sportoŝuojn.',
	'Ili estas tre komfortaj.',
	'Kiel grandaj estas viaj piedoj?',
	'Kio estas la grandeco de viaj ŝuoj?',
	'La grandeco de miaj ŝuoj estas 260 centimetroj.',
	'Mi ŝatas porti iom pli grandajn ŝuojn.',
	'Kiuj markoj de sportoŝuoj estas plej bonaj?',
	'Nuntempe junuloj ŝatas Nike kaj Adidas.',
	'Jes, ili estas bonaj ŝuoj.',
	'Sed ili estas tre multekostaj.',
	'Bonvenon. Kion vi deziras?',
	'Kiom kostas la jako?',
	'Ĉu la pantalono plaĉas al vi?',
	'Tiu jupo estas bela.',
	'Kia estas ĉi tiu robo?',
	'Jen estas mantelo.',
	'Jen estas ankaŭ pluvmantelo.',
	'Bonvole surmetu la jaketon.',
	'Tiu jaketo havas belan koloron.',
	'Mi volas aĉeti ĉi tiun kravaton.',
	'Ĉi tiu ŝalo ne bone sidas al vi.',
	'Demetu ĝin, kaj provu ĉi tiun skarpon.',
	'Ĝi bele sidas al vi.',
	'Mi ofte portas ĉapelon.',
	'Kiu vesto estas en la plej novmoda?',
	'Mallonga jupo estas la plej novmoda.',
	'Mi petas kalsonon kaj ĉemizon.',
	'Mi aĉetos virajn ŝtrumpetojn kaj virinajn ŝtrumpojn.',
	'Ĉu vi havas mamzonon, bluzon kaj piĵamon?',
	'Bonvole donu al mi tiun ĉi ĵerzon.',
	'En vintro ni bezonas dikajn vestojn.',
	'Ŝi tre ŝatas aĉeti belajn vestojn.',
	'Ŝi ĉiam vestas sin tre bele.',
	'Nuntempe oni aĉetas vestojn per interreto.',
	'Ĉu doloras la abdomeno?',
	'Ne, ĉe stomako.',
	'Domaĝe. Bedaŭrinde.',
	'Mi havas kapdoloron.',
	'Mi havas dentodoloron.',
	'Kial vi ne vizitas hospitalon?',
	'Ni iru kune.',
	'Ni iru al la fako de interna kliniko.',
	'Ĉu vi sentas naŭzon?',
	'Jes, kaj mi eĉ vomas.',
	'Kvankam mi sentas naŭzon, mi ne vomas.',
	'Ĉu vi laksas?',
	'Jes.',
	'Kiom ofte vi laksas?',
	'Unu fojon en unu horo.',
	'Kion vi manĝis vespere?',
	'Kutimajn manĝaĵojn.',
	'Vi devas ricevi operacion.',
	'Kiom longe daŭras la operacio?',
	'Ĉu mi ne povas saniĝi per medikamento?',
	'Ĝin prenu tridek minutojn post ĉiu manĝo.',
	'Kian manĝaĵon mi devas eviti?',
	'Evitu grasan manĝaĵon.',
	'Flegistino, mi petas injektilon.',
	'Mi estas malsata.',
	'Ĉu ni iru al manĝejo?',
	'Jen estas bona manĝejo.',
	'Ni eniru.',
	'Kion vi manĝos?',
	'Mi volas manĝi nudelon.',
	'Mi volas manĝi porkaĵon.',
	'Mi petas Hong Shao Rou.',
	'Jen estas.',
	'Ĉu estas rizaĵo?',
	'Bonvole donu al mi glason da akvo.',
	'Jen estas kulero kaj manĝobastonetoj.',
	'Ĉu vi volas drinki?',
	'Ne, dankon.',
	'Ĉu mi rajtas fumi?',
	'Se vi volas.',
	'Jen estas alumeto.',
	'Bonvole donu al mi (unu) cigaredon.',
	'Mi satmanĝis.',
	'Ĉu vi satmanĝis?',
	'Jes, mi satmanĝis. Dankon.',
	'Nu, ĉu ni eliru?',
	'Mi pagos la tuton.',
	'Ĉu ni iru promeni en la Kulturo-Parko?',
	'Bona ideo.',
	'Kio estas la plej vidinda en la parko?',
	'La busto de Zamenhof.',
	'Kiam la busto konstruiĝis?',
	'Tie flugas kolomboj.',
	'Tre paca pejzaĝo.',
	'Kion simbolas la kolombo?',
	'Ĝi simbolas pacon.',
	'Tie troviĝas muzeo.',
	'Ĉu ni vizitu la muzeon?',
	'Estas freŝe kaj agrable.',
	'Estas tre bela panoramo.',
	'Tie vi vidas verdan herbejon.',
	'Jes, certe. Tre bela tago.',
	'Jen estas enirejo.',
	'Kia estas via unua impreso pri la parko?',
	'Tie estas benko.',
	'Ĉu ni sidiĝu ĉi tie?',
	'Vi vidu la belajn florojn en la ĝardeno.',
	'Jes, ili estas tre belkoloraj.',
	'Multaj maljunuloj venas al la parko.',
	'Nuntempe en la socio troviĝas tre multaj maljunuloj.',
	'Tio estas socia problemo.',
	'Ni prenu taksion.',
	'Tie venas taksio.',
	'Mi sidos antaŭe.',
	'Bonvolu, al la stacidomo.',
	'Kie ni estas?',
	'En taksio.',
	'Kio? Vi bone ŝercas.',
	'Ni kuras sur la strato Zamenhof.',
	'Kio estas la domego?',
	'Ĝi estas urbodomo.',
	'Kiom da loĝantoj havas la urbo Ŝanhajo?',
	'Ĉirkaŭ dek milionojn.',
	'Kiom da etaĝoj havas la konstruaĵo?',
	'Sesdek etaĝojn.',
	'Kiom da minutoj ni bezonas de ĉi tie ĝis la stacidomo?',
	'Ĉirkaŭ dek minutojn.',
	'Malpli ol dek minutojn.',
	'Jen, ni atingis nian celon.',
	'Kiom estas la veturkosto?',
	'Vi devas pagi 10 juanojn.',
	'Ŝoforo, jen estas 10 yuanoj.',
	'Bone, ni eliru.',
	'Kie estas la sidloko(seĝo) dek naŭ de la tria vagono?',
	'Tie apud la fenestro.',
	'Mi surmetu la pakaĵon sur breton.',
	'Ĝis Pekino. Sed, kial, sinjoro?',
	'Ankaŭ mi iras ĝis Pekino. Ĉu vi ne enuas?',
	'Jes, iom.',
	'Por kio vi iras al Pekino?',
	'Mia hejmo estas en Pekino.',
	'Mi iras renkonti amikon.',
	'Ĉu vi scias, kie estas la universitato Pekino?',
	'Jes, mi scias.',
	'Ĉu vi bonvolus sciigi al mi la vojon al la universitato?',
	'Jes, mi sciigos al vi.',
	'Mi havas iom da manĝaĵoj. Ni kune manĝu.',
	'Koran dankon, sed mi nun ne volas.',
	'Ho, la pejzaĝo trans la fenestro estas tre bela, ĉu ne?',
	'Jes, tre bela. Ĝi similas al tiu de mia naskoloko.',
	'Mia naskoloko estas Zaozhuang, Shandong provinco.',
	'Bonvenon. Jen estas Esperanto-Muzeo.',
	'Ĝi estas la plej granda Esperanto-Muzeo en la mondo.',
	'Ĝi estis establita en la jaro 2013.',
	'Ĝi estas konstruita en Zaozhuang Universitato.',
	'Ĝi havas diversajn Esperanto-materialojn.',
	'Multaj homoj vizitas la muzeon.',
	'Ankaŭ geknaboj de elementaj lernejoj vizitas ĝin.',
	'De fremdaj landoj ofte venas gastoj.',
	'Ĝi havas ankaŭ tre rarajn materialojn de Esperanto.',
	'Multaj homoj kaj instancoj kontribuas materialojn por la muzeo.',
	'La muzeo estas agnoskita de la urba registaro kiel unu el la gravaj studlokoj por studentoj.',
	'En la muzeo oni povas mem aŭskulti la prononcojn de Esperanto.',
	'Kaj oni ankaŭ povas mem prove paroli en Esperanto.',
	'En ĝi staras la busto de d-ro Zamenhof.',
	'En la muzeo laboras kelkaj fremdlandaj esperantisoj el Koreio kaj Japanio.',
	'La muzeo estas la centro de ĉina Esperanto-Movado.',
	'La muzeo estas simbolo de vivanta lingvo, Esperanto.',
	'Ĉu mi povas uzi interreton?',
	'Jes, vi povas uzi ĝin per tiu ĉi komputilo.',
	'Ĉu vi havas vifion en via ĉambro?',
	'Jes, mia vifio estas tre rapida.',
	'Ĝin vi povas uzi ankaŭ ekster la ĉambro.',
	'Kion vi volas fari per interreto?',
	'Mi volas uzi Fejsbukon.',
	'Ĉu vi havas personan blogon?',
	'Jes, mi havas ĝin.',
	'Mia blogo ĉefe temas pri Ĉinio.',
	'Lastatempe oni multe uzas Guglon.',
	'Jes, per Guglo ni povas serĉi diversajn aferon en interreto.',
	'En Ĉinio ĉu oni povas uzi Guglon?',
	'En Ĉinio ni multe uzas Baidu-on kaj Ŭiĉet-on.',
	'Per saĝtelefono ni povas uzi interreton.',
	'Nuntempe saĝtelefono anstataŭas komputilon.',
	'Jes, nun mi pli ofte uzas saĝtelefonon ol komputilon.',
	'Oni ne povas vivi sen saĝtelefono.',
	'Kiom vi pagas por la uzo de saĝtelefono en unu monato?',
	'Mi pagas ĉirkaŭ tridek juanojn monate.',
	'Ĉu vi uzas multe da datumoj(datenoj)?',
	'Jes, mi uzas tre multe da datumoj por vidi videojn per saĝtelefono.',
	'La mondo multe ŝanĝiĝis.',
	'Nuntempe oni multe uzas nuban komputadon.',
	'Jes, estas tre oportune fari dokumentojn per nubkonserva servo.',
	'Des pli bone, ke ĝi estas senpaga.',
	'Ĉu vi havas personan komputilon?',
	'Jes, mi havas ĝin. Ĝi estas surtabla komputilo.',
	'Ĉu via komputilo havas Vindozon dek?',
	'Jes, mi uzas ĝin.',
	'Vindozo dek estas tre utila.',
	'Ĉu vi havas ankaŭ printilon?',
	'Jes, mi havas, kaj mi ofte uzas ĝin.',
	'Mi ĉiutage printas dokumentojn per ĝi.',
	'Ĉu vi havas koloran printilon?',
	'Ne, mi havas nigra-blankan printilon.',
	'Per komputilo kion vi plej multe faras?',
	'Mi plej multe uzas ĝin por verkado.',
	'Ĉu vi ankaŭ uzas retpoŝton?',
	'Kio estas via retadreso?',
	'Mi ofte ricevas retpoŝtaĵojn.',
	'Jen estas la dosiero, kiun vi sendis al mi.',
	'Mi preparis dosierojn de PPT por la lecionoj de Esperanto.',
	'Mi donos ilin al vi en USB poŝmemorilo (memorbastoneto).',
	'Mi havas ankaŭ printilon krom ekrano, klavaro kaj laŭtparolilo.',
	'Mi nove aĉetis tabulkomputilon.',
	'Mi jam havas ankaŭ tekkomputilon.',
	'Por kio vi uzas la tekkomputilon kaj la tabulkomputilon?',
	'Mi uzas tekkomputilon por verkado de dokumentoj, kaj tabulkomputilon por vidi fotojn kaj videojn.',
	'Mia komputilo ne havas KD-legilon.',
	'Nuntempe oni ne plu uzas k-diskojn.',
	'Komputiloj tre rapide ŝanĝiĝas.',
	'Mi ne povas aĉeti ĉiam la novajn.',
	'Mi aĉetis la nunan jam antaŭ kvin jaroj.',
	'Ĝi ankoraŭ funkcias tre bone.',
	'Longan tempon.',
	'Bone. Dankon. Kaj vi?',
	'Ankaŭ mi bone.',
	'Ĉu vi aŭdis pri Petro?',
	'Ne. Kio okazis al li?',
	'Mi aŭdis, ke li edziĝis.',
	'Ĉu vere?',
	'Ĉu ni vizitu lin?',
	'Unue ni telefonu al li.',
	'Ĉu vi scias, kie estas publika telefono?',
	'Tie troviĝas.',
	'Halo, ĉu mi parolas kun Petro?',
	'Ne. Li ne estas nun hejme.',
	'Kien li iris?',
	'Li iris al lernejo.',
	'Kiam li revenos?',
	'Li revenos je la kvina.',
	'Bonvolu transdiri al li, ke mi vizitos tiam.',
	'Pardonon, sed kiu vi estas?',
	'Mi estas Karlo, amiko de Petro.',
	'Bone, mi transdiros al li.',
	'Koran dankon, ĝis revido.',
	'Kunsido de Esperanto',
	'Saluton!',
	'Vi iom malfruiĝis.',
	'Kio estas hodiaŭa temo?',
	'Ĝi estas Esperantismo.',
	'Prezidanto. Kio estas Esperantismo?',
	'Esperantismo estas uzi Esperanton kiel internacian lingvon kaj ĝin disvastigi.',
	'Kaj kio estas Homaranismo?',
	'Ĝi estas tute persona ideo de dokotoro Zamenhof.',
	'Ĉu Esperanto vere alportos al ni mondpacon?',
	'Ni estu prudentaj. Laŭ mia persona opinio Esperanto povas esti bona ilo por mondpaco.',
	'Ĉu vi pensas, ke Esperanto havas pranktikan utilecon por ni?',
	'Jes, certe.',
	'Mi povas diri, ke ĝi jam ne plu estas arta lingvo, sed natura lingvo havanta vivipovon.',
	'Danke al Esperanto jam multaj homoj komforte travojaĝas tra la mondo.',
	'Kaj ankaŭ por la kompreno kaj aprezo de diverslandaj literaturoj Esperanto estas la plej bona ilo.',
	'Esperanto ĉiam devas esti neŭtrala je ĉiuj flankoj krom lingva problemo.',
	'Pere de Esperanto ni devas forigi la lingvan diskriminacion.',
	'Nu, esperantistoj devas diligente studi, uzi kaj disvastigi Esperanton.',
	'Ni ripozu dum dek minutoj.',
	'Nu, ni diskutu pri la plano de elementa kurso.',
	'Kiam ni ĝin okazigu?',
	'Mi proponas ĝin okazigi en venonta aŭgusto.',
	'Ĉu vi havas alian proponon?',
	'Se ne, ni decidas ĝin okazigi en aŭgusto.',
	'Sekvanta kunveno okazos en venonta sabato.',
	'Ĉu vi iam vojaĝis eksterlanden?',
	'Jes, mi vojaĝis al Japanio kaj Usono.',
	'Ĉu vi ne vojaĝis al Eŭropo?',
	'Ne, mi ankoraŭ ne vojaĝis al Eŭropo.',
	'Mi volas vojaĝi al Eŭropo ĉi somere.',
	'Ĉu vi planas mondvojaĝon?',
	'Jes, mi volas mondvojaĝi rondirante la tutan terglobon.',
	'Kiujn landojn vi planas viziti?',
	'Mi ankoraŭ ne starigis detalan planon.',
	'Ĉu vi iros ankaŭ al Sud-Ameriko?',
	'Jes. Mi tre ŝatas viziti Sud-Amerikon.',
	'En Sud-Ameriko la sezono estas malsama ol ĉe ni, ĉu ne?',
	'Jes. Kaj tial mi kunportas vintrajn vestojn.',
	'Per kiu vojaĝagentejo vi vojaĝas?',
	'Per la vojaĝagentejo Espero.',
	'Ĉu vi vojaĝas grupe aŭ sola?',
	'Mi vojaĝas sola.',
	'Ĉu vi ne timas sola mondvojaĝi?',
	'Ne, mi ne timas. Male, mi pensas, ke tio estas pli interesa.',
	'Jes, vi pravas. Aventuroplena vojaĝo estus pli interesa.',
	'Kia estas via itinero?',
	'Unue mi iros al Japanio, kaj poste al Usono. Kaj de Usono mi plu vojaĝos al kelkaj Sud-Amerikaj landoj, kaj poste mi iros al Eŭropo.',
	'En Eŭropo kiujn landojn vi planas viziti?',
	'Se eblus, mi volus vojaĝi en ĉiuj landoj. Sed tio estas preskaŭ neebla. Mi volas viziti landojn, kie troviĝas multaj esperantistoj.',
	'Mi scias, ke por mondvojaĝo oni devas prepari multon. Kion vi preparis?',
	'Antaŭ ĉio mi preparis la jarlibron de UEA kaj la pasportan servon de TEJO. Kaj mi preparis ankaŭ iom da sukuraj medikamentoj kaj vestoj.',
	'Ĉu vi havas amikojn en la landoj, kiujn vi vizitos?',
	'Jes, en kelkaj landoj, sed ne en ĉiuj landoj.',
	'Ĉu vi jam sciigis ilin pri via vojaĝo?',
	'Jes, jam autaŭ longe, mi sciigis ilin.',
	'Miaj Esperant(ist)aj amikoj, ĉiuj diris, ke ili bonvenigos min.',
	'Ĉu vi mendis la flugbileton?',
	'Jes, mi mendis. Necesas nur, ke mi konfirmu ĝin kelkajn tagojn antaŭ la ekiro.',
	'Vi havas pasporton, ĉu ne?',
	'Jes, jam autaŭ longe mi preparis ĝin.',
	'Mi do deziras al vi agrablan kaj utilan mondvojaĝon.',
	'Bonan vojaĝon!',
	'Ĝis la revido! (Reveninte mi vidos vin.)',
	'Mia nasktotago estas la deka de marto.',
	'Mi naskiĝis en la deka de marto, mil naŭcent naŭdek ok.',
	'Feliĉan naskotagon.',
	'Mi volas ion donaci por via naskotago.',
	'Kion vi deziras ricevi?',
	'Kiel mi mem povas diri?',
	'Vi elektu.',
	'Mi deziras donaci kison.',
	'Dankon, sed ne.',
	'Mi volas inviti vin al vespermanĝo.',
	'Nur tiom?',
	'Sed, por mi tio estas granda donaco.',
	'Ĉiukaze, dankon.',
	'Kioma naskotago?',
	'La dudek-unua.',
	'Ĉu vi ricevis multajn donacojn?',
	'Ĉu vi ricevis gratultelegramon?',
	'Jes, kelkajn.',
	'Ĉu vi venus al mia naskotaga festeno?',
	'Kun plezuro.',
	'Via naskotago estas mia plej granda feliĉo.',
	'Nuntempe oni pli ofte uzas saĝtelefonon ol komputilon.',
	'Per saĝtelefono ni povas fari preskaŭ ĉion.',
	'Antaŭe ĝi estis multekosta, sed nun ne.',
	'Iuj homoj havas du saĝtelefonojn.',
	'Per saĝtelefono ni povas telefoni, komputi, retumi, retpoŝti ktp, ktp.',
	'Ni povas serĉi perditajn amikojn per interreto.',
	'Saĝtelefono multe ŝanĝis nian vivon.',
	'Junuloj tro multe uzas saĝtelefonon.',
	'Ŝajnas, ke ili ne povas vivi sen ĝi.',
	'Per saĝtelefono mi ofte legas novaĵojn.',
	'Kaj oni diras, ke nuntempe ekzistas multaj falsaj novaĵoj en interreto.',
	'Ni devas atenti pri la malbona influo de interreto.',
	'Per diversaj apoj de saĝtelefono ni povas faciligi nian vivon.',
	'Ni povas aĉetumi per saĝtelefono en la dormĉambro.',
	'Estas problemo, ke oni tro ofte uzas saĝtelefonon en ĉiuj lokoj.',
	'En subtera trajno(metroo) ĉiuj pasaĝeroj uzas saĝtelefonon.',
	'Estas ironie, ke saĝtelefono baras la interkomunikadon de homoj.',
	'Ĉu vi povas stiri(ŝofori) aŭton?',
	'Jes, mi povas stiri(ŝofori) aŭton.',
	'Ĉu vi havas stirpermesilon?',
	'Kiam vi akiris la stirpermesilon?',
	'Lastan jaron mi akiris ĝin.',
	'Mi havas ankaŭ la internacian stirpermesilon.',
	'Ĉu vi havas aŭton?',
	'Ne, mi ne havas aŭton.',
	'Ĉe aŭtoŝoforado la plej grava afero estas sintrankviligo.',
	'Lastatempe multaj aŭtoj estas aŭtomataj.',
	'Ĉu vi povas ŝofori ne-aŭtomatajn aŭtojn?',
	'Jes, mi povas ŝofori ne-aŭtomatajn aŭtojn.',
	'Ĝenerale viroj pli bone ŝoforas ol virinoj.',
	'Latatempe en Ĉinioj multaj familioj havas aŭtojn.',
	'Kaj la stratoj estas plenaj je aŭtoj.',
	'En mateno kaj vespero estas tre malfacile ŝofori en urboj.',
	'Mi ofte vojaĝas memŝoforante.',
	'Dum la longtempa ŝoforado oni devas atenti pri la dormemo.',
	'Se mi sentas min dormema, mi ripozas ĉe ripozejoj sur la ekspresa vojo.',
	'Dum iuj feriotagoj la vojimposto estas senpaga.',
	'Lastatempe multiĝas elektroaŭtoj, kiuj ne konsumas benzion.',
	'Kaj ankaŭ aperas memveturantaj aŭtoj, kiuj ne bezonas ŝoforojn.',
	'Kiel ŝanĝiĝos la mondo post dek jaroj?',
	'Mankas benzino ĉe la aŭto.',
	'Kie estas la benzinejo(benzinstacio)?',
	'Bonvole plenigu la benzinujon.',
	'Kiom kostas unu litro da benzino?',
	'Provizu la aŭton per dek litroj da benzino.',
	'Ĉu proksime troviĝas stacio de metroo(subtera trajno)?',
	'Tie dekstre, en la subvojo.',
	'Kie oni vendas biletojn?',
	'Tie oni vendas biletojn.',
	'Unu bileton al Esperanto-Muzeo.',
	'Ĉi tiu elektra trajno estas tre nova.',
	'Kiam la subtera fervojo estis konstruita?',
	'Antaŭ preskaŭ dek jaroj.',
	'Kiom da linioj kursadas en Ŝanhajo?',
	'Kvar linioj.',
	'Ho, la vagono estas tre homplena.',
	'Jes, nun estas la hejmrevena horo.',
	'Ĉu ne estas tro multe da reklamafiŝoj en la vagonaro?',
	'Hodiaŭ estas la epoko de reklamo, ĉu ne?',
	'Tre longaj estas la manteniloj.',
	'Ĉar mi estas malalta, ili estas oportunaj.',
	'Kiam la trajno estas la plej homplena?',
	'En mateno, kiam oni iras la laborejoj.',
	'Vidu, multaj homoj uzas saĝtelefonon en la trajno, ĉu ne?',
	'Jes, nuntempe oni tre ofte uzas ĝin ie ajn.',
	'Iuj telefonas tre laŭte eĉ en la trajno.',
	'Tio estas senetiketa afero.',
	'Ha lo, pardonon. Kie mi estas?',
	'Kiu vojo kondukas al la stacidomo Zaozhuang?',
	'Turnu vin dekstren.',
	'Kiel malproksime de ĉi tie estas la stacidomo Zaozhuang?',
	'Necesas dek minutoj per piedoj.',
	'Ĉu oni povas piediri(marŝi) ĝis tie?',
	'Kiu buso iras tien?',
	'Vi prenu la buslinion tridek unu.',
	'Dankon por via afableco.',
	'Ne transiru aŭtovojn(veturejon).',
	'Bonvolu iri sur trotuaro.',
	'Rapide transiru.',
	'Trafiklampo(Trafiklumo) estas ruĝa.',
	'Gardu vin.',
	'Ne maltrankviliĝu.',
	'Rapide kuru.',
	'Tie venas trafikpolicano.',
	'Kie estas rubujo?',
	'Ne fumu sur strato.',
	'Ĝi estas kamiono.',
	'Homoj observas dekstraflankan trafikon.',
	'La vojo estas ŝtopita de trafikakcidento.',
	'Premu la numerojn.',
	'Halo.',
	'Ĉu tie estas la hejmo de Mansu?',
	'Kun kiu mi parolas?',
	'Vi parolas kun Ĉolsu. Mi estas Ĉolsu.',
	'Mi volas paroli kun Mansu.',
	'Ĉu vi telefonis al mi hieraŭ?',
	'Ne. Kial?',
	'Mi volas vidi vin posttagmeze.',
	'Mi estos iom okupita.',
	'Morgaŭ, do, ĉu bone?',
	'Vi havas eraran numeron.',
	'Mi apenaŭ aŭdas vin.',
	'Bonvolu paroli laŭte.',
	'Ĉu (tie) estas Pekino?',
	'Ĉi tie estas Zaozhuang.',
	'Mi petas vian telefonnumeron.',
	'Ĉu via numero estas unu ok tri kvar ses naŭ nul’ sep du kvin tri?',
	'Pardonu min pri mia malfrua telefono.',
	'La telefono estas okupita.',
	'Ne funkcias la telefono.',
	'Finu telefonon.',
	'Kie okazas ĉi-jara Universala Kongreso de Esperanto?',
	'Ĝi okazos en Varsovio, Pollando, kiu estas la naskiĝloko de Esperanto.',
	'Ĉi-jara kongreso estas la memorkongreso por la centjara jubileo de Esperanto.',
	'En tiu ĉi kongreso partoprenis ĉirkaŭ kvin mil esperantistoj el sesdek landoj.',
	'Kiu estas la prezidanto de L.K.K?',
	'La Alta Protektanto de la kongreso estas la prezidanto de pola parlamento.',
	'Ĝi estas la kongresejo.',
	'La konstruaĵo estas loĝejo.',
	'Antaŭ ĉio ni ricevu nian ĉambronumeron kaj kongresajn dokumentojn ĉe la akceptejo.',
	'Kio estas via ĉambronumero?',
	'Kvin unu tri sur la kvina etaĝo.',
	'Ĉu vi uzas la ĉambron sola, aŭ kune kun iu samĉambrano?',
	'Kio estas via kongresa numero?',
	'Sinjoro Hong el Koreio, ĉu ne?',
	'Jen estas la ŝlosilo de via ĉambro.',
	'Ĉu vi mendis la ekskurson?',
	'Jes, mi mendis la tuttagan ekskurson A-tri kaj la dunotangan B-kvar.',
	'Ĉu vi pagis por la ekskursoj?',
	'Jes, mi pagis al UEA.',
	'Jen estas biletoj por la ekskursoj.',
	'Metinte viajn pakaĵojn en la ĉambro, bonvole vespermanĝu en la manĝejo.',
	'Saluton, sinjor(in)o. Mi venis de Ĉinio.',
	'De kie vi venis?',
	'Kiom da esperantistoj venis el via lando?',
	'Hodiaŭ venis tridek, kaj morgaŭ venos dek plu.',
	'Ĉu vi havas multajn spertojn partopreni en Universala Kongreso?',
	'Ne, mi unuafoje spertas.',
	'Ĉu vi venis per aviadilo(trajno, buso, ŝipo)?',
	'Pri kiu programero vi interesiĝas?',
	'Mi havas intereson pri kongresa universitato kaj kulturaj aranĝoj.',
	'Mi volas partopreni en la faka kunsido de virina agado kaj la ĝenerala kunveno de UEA.',
	'Mi deziras ekhavi multajn novajn amikojn ĉe la interkona vespero ĉi-vespere.',
	'Bonan vesperon, sinjor(in)o. Kie estas bankedejo?',
	'Nur la mendintoj povas partopreni en la bankedo.',
	'Bonvolu doni la bileton.',
	'Bonvole sidiĝu ĉe neokupita seĝo.',
	'Ĉu vi prenos la vegetaran menuon?',
	'Ne, mi prenos la ordinaran.',
	'Sinjoro Liu, ĉu vi iros al la balo hodiaŭ vespere?',
	'Ne, hodiaŭ vespere mi iros al la centro de la urbo por iom turismi.',
	'Pardonon, mi nun devas iri al mia ĉambro. Mi tuj revenos.',
	'Mi lasos mesaĝon sur la rendevua tabulo.',
	'La rendevua tabulo estas en la vestiblo.',
	'Sinjoro Karlo el Germanio serĉas vin.',
	'Mi aŭdis, ke sinjoro Karlo volas inviti al vespermanĝo ĉiujn ĉinajn partoprenantojn.',
	'Ĉu vi ĉeestos la ferman ceremonion?',
	'Ne, mi ne povas, ĉar mi devas iri al la flughaveno ĝis la dek-dua.',
	'Mi iros al Parizo.',
	'Ĝis revido en venonta kongreso.',
	'Kia estas hodiaŭa vetero?',
	'Ŝajnas, ke hodiaŭ ni havos nuban veteron.',
	'Ĉu vi aŭdis veterprognozon?',
	'Jes, mi aŭdis hieraŭ vespere.',
	'Kioma estas hodiaŭa temperaturo?',
	'La plej malalta temperaturo en la mateno estas minus kvar gradoj, kaj la plej alta en la tago estas ĉirkaŭ dek.',
	'Nuntempe la vetero estas iom stranga, ĉu ne?',
	'Jes, estas tro varme malkonvene al vintra vetero.',
	'Jaro post jaro, plifortiĝas la fenomeno de eksterordinara varmo.',
	'Kaj ankaŭ en somero ni ofte havas malvarmdamaĝon.',
	'Hieraŭ matene ni havis tre densan nebulon.',
	'En tiu ĉi vintro ne multe neĝis, ĉu ne?',
	'Ne. Oni diras, ke ni havas vintran sekecon.',
	'Tio ne estos bona por terkulturado.',
	'Vintran guston donas neĝo, frosto, glacio kaj prujno, ĉu ne?',
	'Jes. Oni havos bonan rikolton en aŭtuno, se en vintro estas tre malvarme.',
	'En tiu ĉi vintro infanoj eĉ ne povis sketi.',
	'Ĉu estos varme aukaŭ morgaŭ?',
	'Verŝajne jes.',
	'Lastajn tagojn estas tiel varme, ke oni eĉ ŝvitas en tago.',
	'El sezonoj la plej bona estas printempo.',
	'Por mi, aŭtuno estas pli bona.',
	'Oni diras, ke printempo estas la sezono de virino kaj aŭtuno estas tiu de viro.',
	'Sed nuntempe printempo kaj aŭtuno fariĝis tre mallongaj.',
	'Mi ne scias la kialon. Sed la tuta terglobo fariĝis stranga.',
	'Verŝajne pro la polucio strangiĝas la klimato kaj ankaŭ la sezonoj ŝanĝiĝas eksterordinare.',
	'La sola vojo savi nian terglobon estas nur tio, ke ni ne plu detruu la naturon.',
	'Mi tre ŝatas vojaĝi.',
	'Kiujn landojn vi vojaĝis?',
	'Mi vojaĝis dudek kelkajn landojn.',
	'Laŭ via opinio kiu lando estas la plej bona por vojaĝo?',
	'Ĉinio estas la plej bona lando laŭ mia impreso.',
	'Ĝi havas tre multajn vidindaĵojn.',
	'Multaj vidindaĵoj estas historiaj lokoj.',
	'Multaj turistoj venas el la tuta mondo.',
	'Kiamaniere vi vojaĝas?',
	'Mi ofte vojaĝas sola nur kun unu dorsosako.',
	'Survoje mi renkontas diversajn amikojn.',
	'Mi ŝatas amikiĝi kun fremdlandaj homoj.',
	'Kion vi preparas por internacia vojaĝo?',
	'Unue mi devas prepari pasporton kaj vizon.',
	'Due mi devas havi monon kaj tempon.',
	'Mi ĉiam kunportas medikamentojn kaj manĝaĵojn.',
	'Mi ŝatas vojaĝi mem ŝoforante.',
	'Mi memŝofore vizitis multajn lokojn en Ĉinio.',
	'En diversaj urboj mi renkontis esperantistojn.',
	'Ili tre afable gvidas min en siaj urboj.',
	'Fojfoje ili gastigas min ĉe siaj hejmoj.',
	'Mi de tempo al tempo gastas ĉe esperantistoj.',
	'Mi utiligas Pasportan Servon de TEJO.',
	'Ĝenerale esperantistoj estas tre afablaj.',
	'En Ĉinio ekspresaj vojoj estas tre bonaj.',
	'Kaj nuntempe mi ĉiam uzas navigilon.',
	'Saĝtelefona navigilo estas tre utila.',
	'Sen navigilo nuntempe oni ne povas ŝofori, nek vojaĝi.',
	'Ĉiuj aŭskultantoj laŭte aklamis.',
	'Ili babilis inter si dum longa tempo.',
	'Ne balbutu en Esperanto.',
	'Dum dormado li ofte deliras.',
	'Bonvole diru la veron.',
	'Ne englutu ĝin.',
	'La knabo lernis kiel fajfi.',
	'Ili faras grandan bruon.',
	'Li flustris al ŝi sian amon.',
	'Gargaru la gorĝon per akvo.',
	'Li rapide glutis la medikamenton.',
	'Li grincigis la dentojn al ŝi.',
	'Bonvole gustumu la manĝaĵon.',
	'Li kaĵolis ŝin per dolĉaj vortoj.',
	'Mi volas kisi vin.',
	'Li knaras dum dormado.',
	'Ne kraĉu sur la stratoj.',
	'Ili laŭte kriis al la kantisto.',
	'La hundo lekas akvon per lango.',
	'Ŝi ŝatas maĉi maĉgumon.',
	'Li ofte mensogas.',
	'Ne mordu viajn fingrojn.',
	'Li estas muta.',
	'La putra viando naŭzas min.',
	'Li rakontis al mi la aferon.',
	'Ili ridis laŭte.',
	'Ne riproĉu aliajn.',
	'Li salivumas, ĉar ĝi aspektas tre bongusta.',
	'Li singultas senĉese.',
	'Li sputis multan sangon hieraŭ.',
	'La bebo suĉas la mamon de la pantrino.',
	'Ili manĝegas kaj ŝmacas brue.',
	'Li subite ternis kiel ĉevalo.',
	'Li tre ofte trompas per vortoj.',
	'Li tusas pro gripo.',
	'Voku lin al mi.',
	'Mi vomis pro naŭzo.',
	'Mi jam antaŭvidis tion.',
	'Mi multe cerbumis pri tio.',
	'Ĉu vi deziras ĝin?',
	'Oni esperas pacon.',
	'Ŝi forgesis lin.',
	'Mi imagis, ke li aperos al mi.',
	'Li instruas Esperanton.',
	'Li kapbatis la amikon.',
	'La knabo kapjesis du fojojn.',
	'Mi ne povas konjekti la rezulton.',
	'Ĉu vi memoras min?',
	'Mi ne pensas tiel.',
	'Mi ofte sonĝas en la nokto.',
	'Li studas diligente.',
	'Mi supozas, ke ĝi estas ĝusta.',
	'Nun mi rememoras la tagojn.',
	'Ili revis pri la sukceso.',
	'Mi ne volas iri al vi.',
	'Ne zorgu pri la infano.',
	'Li baraktis kontraŭ la morto.',
	'La infano dronis en akvon.',
	'Li ekzercas sin ĉiutage.',
	'Folioj falas en aŭtuno.',
	'Li klinis sian kapon ĉe ŝiaj ŝultroj.',
	'Li kuŝas sur la lito.',
	'Ili ripozas sub la arbo.',
	'Li ruliĝis de sur la monteto.',
	'Ŝi turnis sin al li.',
	'Ili aplaŭdis lin pro lia sukceso.',
	'Ne batu viajn amikojn.',
	'Ŝi brakumis la infanojn.',
	'La milito detruis la urbon.',
	'Ni elektis lin kiel nian prezidanton.',
	'Li atenteme elpikis la najlon.',
	'Li etendis la manon al ĝi.',
	'Ne faru maldecajn agojn.',
	'La birdo flugis al la arbo.',
	'Li frapis la pordon.',
	'Li frotis la manojn pro malvarmo.',
	'Li gestis per manoj por montri sian jeson.',
	'Ne multe gratu la haŭton.',
	'Mi havas multajn amikojn.',
	'Li ĵetis ŝtonon al la arbo.',
	'La infano povas kalkuli per fingroj.',
	'Li karesis ŝiajn harojn.',
	'Ili konstruis grandan domon.',
	'Levu manon, se vi scias.',
	'Mallevu manon, se vi ne scias.',
	'Li scias, kiel manipuli la ŝraŭbilon.',
	'Li ĉiam manpremas tro forte.',
	'Montru al mi vian hejmtaskon.',
	'Li pafis la birdon por ĝin kapti.',
	'Li palpis ĉirkaŭe en la mallumo.',
	'Ili pendigis Jesuon sur la arbo.',
	'Ŝi pikis lin per pinta ungo.',
	'Ni plantas arbojn en la monto.',
	'Premu la butonon por movi ĝin.',
	'Jen vi prenu ĝin.',
	'Li svingis sian pugnon.',
	'Ŝi puŝis la pordon.',
	'Mi ricevis multajn donacojn.',
	'Li skribas tre bele.',
	'Li ŝoforas tre bone.',
	'Li stiris la aŭton tutan nokton.',
	'La registaro subpremis ilin.',
	'Mi subtenas ilian projekton.',
	'Li svingis la manojn por voki ŝin.',
	'Tenu ĝin firme.',
	'Li tiris la aŭton per granda forto.',
	'Mi tranĉis la ŝnuron.',
	'Ni transportas ilin per aŭtoj.',
	'Li ne turnis sian dorson.',
	'La pilko turniĝas tre rapide.',
	'Ne tuŝu la fenestron.',
	'Li viŝis sian vizaĝon.',
	'Mi flaras nun la odoron de floro.',
	'Se vi ne spiras, vi mortas.',
	'Ne ronku dum la dormado.',
	'Li nazridis ŝian proponon.',
	'La panjo purigas la nazon de la infano.',
	'Ĉiam elfluas nazmuko el liaj nazoj.',
	'Mia korpo estas sana.',
	'Mia menso ankaŭ estas sana.',
	'Homo havas spiriton.',
	'Lia animo revenis al la ĉielo.',
	'Lia koro malsanas.',
	'Lia koro estas tre bona.',
	'Ĉiu havas sian ideon.',
	'Lia penso estas ĝusta.',
	'Homoj havas karnon kaj animon.',
	'La fiŝo havas multajn ostetojn.',
	'Sango elfluas el la nazo.',
	'Liaj muskoloj estas tre fortaj.',
	'Ŝia haŭto estas tre blanka.',
	'Homa korpo havas multajn organojn.',
	'Ni havas 4 membrojn: 2 brakojn kaj 2 gambojn.',
	'Ĝi estas la skeleto de homo.',
	'Oni ne ŝatas grandan kapon.',
	'Cerbo estas la plej grava.',
	'Cerebelo estas cerbeto.',
	'Ŝafoj havas 2 kornojn.',
	'Ŝiaj haroj estas tre nigraj.',
	'Lia blonda hararo plaĉas al mi.',
	'Vizaĝo estas la spegulo de animo.',
	'Li havas malkontentan mienon.',
	'Ŝi havas tre belan frunton.',
	'Troviĝas 2 linioj ĉe lia glabelo.',
	'Ŝiaj brovoj aspektas kiel luno.',
	'La palpebroj estas tre pezaj, kiam oni sentas dormemon.',
	'Ŝiaj okulharoj estas tre longaj.',
	'Miaj okuloj estas miopaj.',
	'Liaj pupiloj malfermiĝis grande.',
	'Li havas altan nazon.',
	'La dekstra naztruo estas ŝtopita.',
	'Ŝiaj vangoj ruĝiĝis.',
	'Li havas belajn lipharojn.',
	'Lia buŝo estas granda.',
	'Li havas longan filtrumon.',
	'Ŝiaj lipoj estas tre belaj.',
	'Li havas blankajn dentojn.',
	'Li mordis per antaŭdentoj.',
	'La mueldeontoj estas grandaj.',
	'Ni devas brosi ankaŭ gingivon. (dentkarno)',
	'Li havas longan langon.',
	'Salivo elfluas el lia buŝo.',
	'Mia gorĝo doloras pro gripo.',
	'Manĝaĵo trapasas ezofagon.',
	'Lia mentono estas mallonga.',
	'Li havas longan barbon.',
	'Liaj vangoharoj estas belaj.',
	'Ŝi ĉagreniĝas pro la angulaj makzeloj.',
	'La oreloj de la reĝo estis longaj.',
	'Bone ŝtopu la oreltruojn.',
	'Ŝi havas longan kaj belan kolon.',
	'Io varma sentiĝis ĉe la nuko.',
	'Liaj ŝultroj estas tre pezaj.',
	'Li portas sakon sur la dorso.',
	'Li havas larĝan bruston.',
	'La bebo suĉas mamojn de la panjo.',
	'Virinaj cicoj estas pli grandaj ol la viraj. (mampinto, papilo)',
	'Li havas multajn harojn ĉe akseloj.',
	'Liaj brakoj estas longaj.',
	'Mia antaŭbrako vundiĝis.',
	'Nigra makulo ĉe la kubuto.',
	'Mi portas horloĝon ĉe pojno. (mankolo, manradiko, manartiko)',
	'Homoj havas du manojn.',
	'Homoj havas 10 fingrojn.',
	'Troviĝas linioj sur la polmo.',
	'Li skribis ion sur sia mandorso.',
	'Li levis la polekson por jesi.',
	'Montra fingro estas la 2-a fingro.',
	'Meza fingro estas la plej longa.',
	'Ŝi portas edziĝoringon sur la ringa fingro.',
	'Li ne povas bone movi la malgrandan fingron. (eta)fingro',
	'Li ofte mordas la ungojn.',
	'Oni manĝas la ripoviandon de bovo.',
	'Mi havas doloron ĉe ventro.',
	'Lia umbiliko estas granda.',
	'Doloras mia abdomeno.',
	'Mia stomako estas plena.',
	'Li havas hepatokanceron.',
	'Ĉe pulmo troviĝas iom da akvo.',
	'Reno estas tre grava organo.',
	'Koro pumpas sangon.',
	'Galveziko estas parto de hepato.',
	'Intesto de homoj estas tre longa.',
	'Dika intesto ĉirkaŭas la maldikan inteston.',
	'Lieno kuŝas maldekstre.',
	'Duodeno estas parto de maldika intesto.',
	'Cekumo estas la unua parto de dika intesto.',
	'Rektumo estas la fina parto de dika intesto.',
	'Urino kolektiĝas en urinveziko.',
	'Pankreato produktas insulinon.',
	'Ŝi havas belan talion.',
	'Maljunuloj havas doloron ĉe lumbo.',
	'Li staras kun la manoj al la koksoj.',
	'Homoj sidas sur sidvangoj. (postaĵo, pugo)',
	'Hundo havas longan voston.',
	'Li vundiĝis ĉe dekstra ingveno.',
	'Fekaĵo eliras el la anuso.',
	'Liaj femuroj estas dikaj.',
	'La infano sidas sur la genuoj de la patrino.',
	'La kanbo havas longajn krurojn.',
	'Sur lia suro sidas moskitoj.',
	'Tibiokarno estas suro.',
	'Li havas nur unu gambon.',
	'Ŝiaj piedoj estas malgrandaj.',
	'Ŝiaj piedkoloj estas maldikaj.',
	'Li havas grandan makulon sur la pieddorso.',
	'Miaj plandoj estas tro plataj.',
	'Li havas 12 piedfingrojn.',
	'Liaj haluksoj estas tro grandaj.',
	'Ŝi kolorigis la piedungojn ruĝaj.',
	'Ŝi turnis sin sur la kalkanoj.',
	'Atentu! Ĝi estas danĝera.',
	'Bone esploru la aferon.',
	'Ne grimacu!',
	'Ŝi ĉiam okulridas al mi.',
	'Ne okulumu al la virino.',
	'Li ĉiam palpebrumas.',
	'Ne ploru, mia kara.',
	'Kial vi rigardaĉas al mi?',
	'Li rigardis tra la fenestro.',
	'Mi vidas la ĉielon.',
	'Mi ne bone aŭdas vin.',
	'Ili aŭskultas lian prelegon.',
	'Ili tro laŭte bruas.',
	'Ne parolu tro laŭte. Mi ne estas surda.',
	'La birdoj kantas orelŝire.',
	'Li eksidis sur la seĝo.',
	'Li ekstaris kaj eliris el la ĉambro.',
	'Ili genuis kaj preĝis al la Dio.',
	'La knabo iris al la lernejo.',
	'La knabino kaŭris en la Angulo de la ĉambro.',
	'Kuru rapide al la monto.',
	'Ili marŝis al la placo.',
	'Ili paŝis malrapide.',
	'La knabo piedbatis la pilkon.',
	'Ili piediris anstataŭ veturi.',
	'Li piedpremis la vermon.',
	'La infanoj saltas sur la lito.',
	'Li silente sidas sur la seĝo.',
	'Bonvole sidiĝu ĉi tie.',
	'La arbo staras antaŭ la domo.',
	'Bonvole stariĝu.',
	'Li stumblis pro malsano.',
	'Ili tretis la falintajn kukojn.',
	'Venu al mi morgaŭ matene.',
	'Li povas digesti ĉiujn manĝaĵojn.',
	'Se oni ne fekas, oni mortas.',
	'Li furzas tre ofte.',
	'Lia rakonto ege kortuŝis ĉiujn.',
	'Ŝi naskis bebon.',
	'La infano pisas ĉe la pordo.',
	'La sangotubo pulsas forte.',
	'Li sangas je la nazo.',
	'La bebo urinis sur la lito.',
];
