L_course = [
    'Esperanto estas facila kaj interesa.',
    'La rozo estas bela floro.',
    'Mi estas diligenta studento',
    'Ni estas koreaj Esperantistoj.',
    'Vi estas tre saĝa.',
    'Vi estas bona kuracisto.',
    'Li skribos leteron al vi en Esperanto.',
    'Vi estas diligentaj.',
    'Vi estas bonaj kuracistoj.',
    'Li estas bona knabo.',
    'Ŝi estas saĝa knabino.',
    'Ĝi estas granda kaj bela domo.',
    'Ili estas bonaj homoj.',
    'Li havas sian domon.',
    'Ŝi amas siajn edzon kaj filon.',
    'Ili havas siajn librojn.',
    'Oni parolas en Esperanto.',
    'La hundo estas fidela besto.',
    'Li estas bona instruisto.',
    'Ŝi havas grandan domon.',
    'Ĉu li estas bona knabo?',
    'Jes, li estas bona knabo.',
    'Ne, li ne estas bona knabo.',
    'Li parolas bone en Esperanto.',
    'Ĉu li parolas bone en Esperanto?',
    'Jes, li parolas bone en Esperanto.',
    'Ne, li ne parolas bone en Esperanto.',
    'Ĉu la knabo estas saĝa?',
    'Jes, la knabo estas saĝa.',
    'Ne, la knabo ne estas saĝa.',
    'Ĉu la fraŭlino estas bona amikino?',
    'Jes, la fraŭlino estas bona amikino.',
    'Ne, la fraŭlino ne estas bona amikino.',
    'Ĉu la pomo estas granda frukto?',
    'Jes, la pomo estas granda frukto.',
    'Ne, la pomo ne estas granda frukto.',
    'Ĉu la rozo estas blanka?',
    'Jes, la rozo estas blanka.',
    'Ne, la rozo ne estas blanka.',
    'Ĉu la kato estas granda?',
    'Jes, la kato estas granda.',
    'Ne, la kato ne estas granda.',
    'Ĉu Esperanto estas facila?',
    'Jes, Esperanto estas facila.',
    'Ne, Esperanto ne estas facila.',
    'Kie estas la libro?',
    'La bovo estas diligenta.',
    'la suno, la ĉielo, la tero',
    'Li estas la Zamenhof de Koreio.',
    'Vi estas la unua en nia klaso.',
    'Li estas la plej rapida el la sportistoj.',
    'Kio estas Esperantismo?',
    'Kiu lernas korean lingvon?',
    'Kia estas Seulo?',
    'Kies domo estas bela?',
    'Kies libro estas interesa?',
    'Kie vi loĝas?',
    'Kiam vi laboras?',
    'Kiom ĝi kostas?',
    'Kiom da libroj vi havas?',
    'Kial vi lernas Esperanton?',
    'Kial li vizitis min?',
    'Kiel vi fartas?',
    'Mi lernas internacian lingvon.',
    'Li estas honesta komercisto.',
    'La domo estas tre bela.',
    'Ĉu vi iras al la lernejo nun?',
    'Ĉu vi amas vian malamikon?',
    'Mi eklernis Esperanton antaŭ du jaroj.',
    'Ĉu vi ambaŭ manĝis multe en la manĝejo?',
    'Kiam vi vizitis Francion?',
    'Ŝi lernos ĉinan lingvon baldaŭ.',
    'Ĉu vi vizitos Ĉinion?',
    'Mia filo venos morgaŭ.',
    'Mi iru al la kursejo.',
    'Ni manĝu bonguste.',
    'Ni ekiru.',
    'Ni kantu kune.',
    'Li laboru.',
    'Vi venu morgaŭ matene.',
    'Vi ne plu memoru la aferon.',
    'Bonvole, dormu trankvile. (Bonvolu, dormi trankvile.)',
    'Estas al mi tre ĝoje, ke mi renkontis vin.',
    'La fakto, ke li estas sincera, estas vera.',
    'Mi ĝojas pro tio, ke vi fartas bone.',
    'Ĉu vi pensas, ke Esperanto estas utila?',
    'La patrino deziras, ke gefiloj studu diligente.',
    'Kio vi estas? (Kio estas vi?)',
    'Mi estas instruisto.',
    'Mi estas oficisto.',
    'Kion vi lernas?',
    'Mi lernas Esperanton.',
    'Kiu li estas? (Kiu estas li?)',
    'Li estas Lazaro Ludoviko Zamenhof.',
    'Kiun vi renkontis?',
    'Mi renkontis mian amikon.',
    'Kio estas la tulipo?',
    'La tulipo estas floro.',
    'Kiu estas la tulipo?',
    'Ĝi estas la tulipo.',
    'Kiu sinjoro laboras diligente?',
    'La alta sinjoro laboras diligente.',
    'Kiun floron vi ŝatas?',
    'Mi ŝatas rozon.',
    'Kiu besto kuras rapide?',
    'La hundo kuras rapide.',
    'Kia estas la flegistino?',
    'La flegistino estas afabla.',
    'Kia urbo estas Seulo?',
    'Seulo estas bela kaj granda urbo.',
    'Kia libro ĝi estas?',
    'Ĝi estas lernolibro.(lerno-libro)',
    'Kian koloron ĝi havas?',
    'Ĝi estas ruĝa. Ĝi havas ruĝan koloron.',
    'Kies libro ĝi estas?',
    'Ĝi estas mia libro.',
    'Ĝi estas libro de mia patro.',
    'Kies libron vi havas?',
    'Mi havas lian libron.',
    'Mi havas libron de la amiko.',
    'Lia domo estas bela.',
    'La domo de lia patro estas bela.',
    'Mi loĝas ekster Seulo.',
    'Kie situas Koreio?',
    'Koreio situas en Azio.',
    'Kie estas Esperanto-Kulturcentro?',
    'Esperanto-Kulturcentro sidas en la centro de Seulo.',
    'Kien vi iras?',
    'Mi iras hejmen.',
    'Mi lernas Esperanton, ĉar ĝi estas facila kaj utila.',
    'Mi lernas Esperanton por lingva egaleco de homaro.',
    'Kial doktoro Zamenhof kreis Esperanton?',
    'Doktoro Zamenhof kreis Esperanton por mondpaco.',
    'Kial vi verkis la libron?',
    'Mi verkis la libron, por ke vi lernu Esperanton facile.',
    'Kiel vi fartis?',
    'Mi fartis bone kun miaj familianoj.',
    'Kiel li veturis al Ĉinio?',
    'Li veturis al Ĉinio per aviadilo.',
    'Kiel vi solvis la problemon?',
    'Mi solvis la problemon saĝa (=kun saĝo).',
    'Kiel afabla ŝi estas!',
    'Kia malsaĝulo li estas!',
    'Kiam vi lernas Esperanton?',
    'Mi lernas Esperanton vespere.(=en la vespero)',
    'Kiam vi eklernis Esperanton?',
    'Kiam vi forlasos Koreion?',
    'Mi forlasos Koreion post unu jaro.',
    'Kiom da Esperantistoj estas en la ĉambro?',
    'Dek homoj estas en la ĉambro.',
    'Kiom da tagoj vi restos en Koreio?',
    'Mi restos dum tri tagoj en Koreio.',
    'Kiom da familianoj vi havas?',
    'Mi havas kvin familianojn.',
    'Kiom da mono vi havas?',
    'Mi havas kvinmil ŭonojn.',
    'Kiom da akvo estas en la akvujo?',
    'Multe da akvo estas en la akvujo.',
    'Paroli estas facile, sed fari estas malfacile.',
    'Ĉu vi volas viziti malnovajn urbojn?',
    'Mia hobio estas kolekti poŝtmarkojn.',
    'Estas la horo ekiri al mia domo.',
    'La libro estas malfacila por legi.',
    'Mi laboras por gajni monon.',
    'Ĉu li estas via dua filo?',
    'La unuaj libroj de Esperanto estas legindaj.',
    'Unue, ni devas labori diligente.',
    'Milionoj da homoj kantas en la placo.',
    'Sen saĝo oni estas nulo.',
    'Du kaj(plus) tri estas(faras) kvin.',
    'Dek minus kvin estas(faras) kvin.',
    'Okoble tri estas(faras) dudek kvar.',
    'Dudek dividite per tri estas (faras) ses kaj restas du.',
    'Kioma horo estas?',
    'Estas la tria (horo) kaj dudek minutoj.',
    'Estas la sepa (horo) kaj unu minuto.',
    'Estas la kvina (horo) kaj duono.',
    'Estas dek minutoj antaŭ la sepa (horo).',
    'Kio vi estas? (Kio estas via profesio?)',
    'Kio estas homaranismo?',
    'Tio estas la domo de mia amiko.',
    'Io estas en la tirkesto.',
    'Ĉio estas en via koro.',
    'Nenio estas en la monujo.',
    'Kiu vi estas? (= Kio estas via nomo?)',
    'Tiu estas sinjoro Kim.',
    'Iu vokis min sur la strato.',
    'Mi disdonis la libron al ĉiu.',
    'Ĉiuj diras, ke Esperanto estas internacia lingvo.',
    'Neniu estas en la ĉambro.',
    'Kia estas la fraŭlino el viaj klasanoj?',
    'Tia koloro ne plaĉas al mi.',
    'Ŝi ĵetis iajn vortojn al mi.',
    'Ĉia dono estas bono.',
    'Nenia ideo aperis en mia kapo.',
    'Kiu lando estas vizitinda?',
    'Tiu floro floras en la kamparo.',
    'Iu knabo perdis la vojon.',
    'Ĉiu persono havas propran karakteron.',
    'Neniu laboristo estas en la laborejo.',
    'Ties koloro estas blanka.',
    'Ies voĉon mi aŭdis.',
    'Ĉies lingvo estas Esperanto.',
    'Nenies okuloj favoris al li.',
    'Kien vi volas iri?',
    'Tie estas mia preĝejo.',
    'Ie loĝas mia malnova amiko.',
    'Ĉie loĝas bonaj homoj en la mondo.',
    'Nenie mi vidis tiel honestan personon.',
    'Kiel mi povas iri al Pekino?',
    'Ankaŭ mi pensas tiel.',
    'Iel ŝi solvos sian hejmtaskon.',
    'Ĉiel li helpis al mi.',
    'Vi neniel venkos lin.',
    'Kial vi lernas la lingvon?',
    'Tial mi ridegis gaje.',
    'Ial li ne venis hodiaŭ.',
    'Tio estas ĉial bona.',
    'Nenial li koleras.',
    'Tiam li ne estis en la domo.',
    'Iam vi povos rerenkonti lin.',
    'Ĉiam ŝi pensas pri vi.',
    'Neniam mi atendos ŝin.',
    'Kiom da landoj vi vojaĝis?',
    'Tiom da libroj ankaŭ mi havas.',
    'Donu iom da sukero.',
    'Neniom da akvo estas en la akvujo.',
    'Ĉu vi deziras havi ĉiom?',
    'Kiom da Esperantistoj estas en Japanio?',
    'Multaj Esperantistoj estas en Japanio.',
    'Mi havas kvinmil usonajn dolarojn.',
    'Ĉiu havas sian propran guston.',
    'Mi vokis ĉiun el ili aparte.',
    'Ĉiuj rapide kuris, ĉiu revenis al sia hejmo.',
    'Se mi estus riĉa, mi aĉetus la aŭton.',
    'Se mi estus sana, mi povus vivi longe.',
    'Se mi havus flugilojn, mi flugus al vi.',
    'Se mi estus dio, mi povus fari tion.',
    'Ĉu vi volus trinki kafon?',
    'Ĉu vi povus porti ĝin al mi?',
    'Se vi lernos Esperanton, mi donos lernolibron al vi.',
    'Se vi lernus Esperanton lastjare, mi donus lernolibron al vi.',
    'Je kioma horo li venis al la lernejo?',
    'Li venis al la lernejo je la 7-a horo matene.',
    'Li estas alta je 2 metroj.',
    'Mi prenis je ŝia mano.',
    'Vi havas rajton je tio.',
    'Li estas vundita je la piedo.',
    'Estas la dua horo kaj dek minutoj.',
    'Hodiaŭ neĝas.',
    'Pluvas multe.',
    'Estas varme.',
    'Estas trankvile.',
    'Estas agrable.',
    'Estas necese.',
    'Estas komforte.',
    'Vojaĝi kun Esperanto estas interese.',
    'Estas mirinde, ke li sukcesis.',
    'Li studas tiel diligente kiel mi.',
    'La kato kuras tiel rapide kiel la hundo.',
    'Li estas tiel saĝa kiel Zamenhof.',
    'Li estas tiel afabla kiel mia instruisto.',
    'Ŝi estas tiel eleganta kiel mia fratino.',
    'Li estas tiel bona kiel sia patro.',
    'Ĉu li estas pli saĝa ol mi?',
    'En Esperanto li parolas pli flue ol angla lingvo.',
    'Li estas malpli laborema ol ŝi.',
    'Ŝi parolas pri la afero malpli serioze ol mi.',
    'Li estas la plej saĝa el miaj klasanoj.',
    'Ĉi tiu birdo flugas la plej malrapide el la birdoj.',
    'Li estas unu el la plej famaj verkistoj en la mondo.',
    'Mi estas la malplej aktiva el miaj familianoj.',
    'Mi estas manĝanta la bongustaĵon.',
    'Mi estas laborinta en la laborejo.',
    'Mi estas ironta al la domo de mia amiko.',
    'La kato estis manĝanta la fiŝon.',
    'La kato estis manĝinta la fiŝon.',
    'La kato estis manĝonta la fiŝon.',
    'Mi estos instruanta korean lingvon.',
    'Mi estos instruinta korean lingvon.',
    'Mi estos instruonta korean lingvon.',
    'La pordo estas fermata de la knabo.',
    'La pordo estas fermita de la knabo.',
    'La pordo estas fermota de la knabo.',
    'La domo estis konstruata de la laboristoj.',
    'La domo estis konstruita de la laboristoj.',
    'La domo estis konstruota de la laboristoj.',
    'La ĉielo estos kovrata de la nubo.',
    'La ĉielo estos kovrita de la nubo.',
    'La ĉielo estos kovrota de la nubo.',
    'Mi ludas la pianon.',
    'La piano estas donacita de miaj gepatroj.',
    'Mi ludas la pianon, kiu estas donacita de miaj gepatroj.',
    'Doktoro Zamenhof kreis Esperanton en la jaro 1887.',
    'Mi lernas Esperanton, kiun doktoro Zamenhof kreis en la jaro 1887.',
    'Mi havas la belan ĝardenon.',
    'La koloro de la ĝardeno estas verda kaj flava.',
    'Mi havas la belan ĝardenon, kies koloro estas verda kaj flava.',
    'Mi manĝis ion, kio estis bongusta.',
    'Li ne komprenis tion, kion mi diris.',
    'Mi batis mian fraton, kio estas malbona.',
    'Mi batis mian amikon, kiu estis maldiligenta.',
    'La brila, kion mi vidis, estis orero.',
    'Mi vizitis mian hejmlokon.',
    'Mi loĝis en mia hejmloko antaŭ dek jaroj.',
    'Mi vizitis mian hejmlokon, kie mi loĝis antaŭ dek jaroj.',
    'Mi renkontis lin hodiaŭ matene.',
    'Mi promenis en la parko hodiaŭ matene.',
    'Mi renkontis lin hodiaŭ matene, kiam mi promenis en la parko.',
    'Ankaŭ mi estas komencanta Esperantisto.',
    'Ĉu li ankoraŭ laboras en la laborejo?',
    'Mi apenaŭ kaptis la kurantan trajnon.',
    'Mi ekiros, apenaŭ mi finos la laboron.',
    'Ŝi ne diris eĉ unu vorton antaŭ mi.',
    'Li loĝas kun sia panjo for de la urbo.',
    'Ili forlasis la domon hieraŭ nokte.',
    'Jam estas tempo iri hejmen.',
    'Jen, li malaperis subite',
    'Jen estas la seĝo por vi.',
    'Li us foriris kun sia amikino',
    'Mi amas ŝin kiel min mem.',
    'Nur du homoj vizitis min hodiaŭ matene.',
    'Ĉu li estas la plej bona el viaj konatoj?',
    'Ŝi estas pli ĉarma ol rozo.',
    'La soldatoj marŝis kelkajn paŝojn plu.',
    'Mi tuj rimarkis, ke li estas honesta.',
    'Li aspektas almenaŭ kvardek jara.',
    'Baldaŭ li venos al mia domo.',
    'Ĉirkaŭ dek samideanoj estas en la ĉambro.',
    'Mi renkontis lin hieraŭ en mia laborejo.',
    'Hodiaŭ li estas serioze malsana.',
    'Morgaŭ mi iros al la preĝejo kun miaj gefiloj.',
    'Ŝi estas ja sincera oficistino.',
    'Jes, li ĉiam kaj ĉie diras la veron.',
    'Li ne venis al mi hieraŭ vespere.',
    'Li estas dormanta kvazaŭ mortinto.',
    'Aŭdinte la nova on, li tre surpriziĝis.',
    'Tro da kuiristoj kaĉon difektas.',
    'Li hastas tro urĝe.',
    'Nun li estas tre okupita pro la ofico.',
    'Miaj amikoj preskau ciam estas kun mi.',
    'La birdo sidas supre de la arbo.',
    'La birdo sur la ĉielo flugas suden rapide.',
    'La figuro de la fluganta birdo estas vere bela.',
    'Li rakontis al mi sincere amike.',
    'Mi iras al mia domo, kiu sidas en la nordo de Seulo.',
    'Mia onklo donis la libron al mi.',
    'Ŝi diligente laboris anstataŭ mi.',
    'Antaŭ la domo staras la arboj.',
    'Li revenis al la domo antaŭ unu horo.',
    'Apud mia domo loĝas mia amika amiko.',
    'Ŝi restas ne ĉe mia domo, sed apud la mia.',
    'La luno rondiras ĉirkaŭ la tero.',
    'Kiom da homoj estas en la ĉambro?',
    'Kiom da mono estas en via monujo?',
    'De kiu vi ricevis la ruĝan floron?',
    'Ĝi estas la libro de mia patro.',
    'Li kuris ŝvitante dum du horoj laŭ la rivero.',
    'Li staras ekster la pordo kun pluvo.',
    'Ŝi estas la plej saĝa el la klasanoj.',
    'La flago pendas el la fenestro.',
    'Ĉu vi loĝas en tiu ĉi urbo kun viaj gepatroj?',
    'Mi laboris ĝis la kvina horo hieraŭ.',
    'Inter du landoj estas etaj insuloj.',
    'Je kioma horo vi vekiĝis?',
    'Mi vekiĝis je la kvina frumatene.',
    'La domo staras kontraŭ la rivero.',
    'Krom Esperanto, mi povas paroli germanan lingvon.',
    'Mi volas vivi kun vi feliĉe en bela domo.',
    'Sen libero, ni ne povas vivi.',
    'La akvo fluas laŭ la rivero.',
    'Malantaŭ la domo staras granda roko.',
    'Malgraŭ la problemoj, la afero estis solvita de li.',
    'Ĉu vi volas vojaĝi tra la mondo per aviadilo?',
    'La patrino disdonis la pomojn po tri al la filoj.',
    'Li pasis preter mi sen saluto.',
    'Nun temas pri internacia politika situacio.',
    'Mi laboras kun plezuro por mia estonto.',
    'Mi pagis kvinmil ŭonojn por la nova libro.',
    'Ĉu ŝi ploras pro malĝojo aŭ malsano?',
    'Sub la ponto, la ŝipo pasas malrapide.',
    'La libelo flugas libere super la rivero.',
    'Ĉu la manĝaĵo estas sur la tablo?',
    'Tra la kamparo, ĉevaloj kuras rapide.',
    'Ĉu li loĝas trans la monto?',
    'La birdoj flugis trans la maron.',
    'Post unu jaro, mi povos paroli bone en Esperanto.',
    'Ĉu la knaboj estas bonaj amikoj?',
    'Ĉu ili estas malbonaj najbaroj?',
    'Ĉu li estas diligenta laboristo?',
    'La dormemulo estas maldiligenta.',
    'Via koro povas esti la plej granda en la mondo.',
    'La ĉambro de mia filino estas malgranda.',
    'Lia patro estas fama artisto.',
    'La bopatro estas la patro de mia edzino.',
    'Mia filo estas verkisto.',
    'Ĉu via bofilo estas inĝeniero?',
    'Kiom da fratoj vi havas?',
    'Li estas mia dua bofrato.',
    'Kiom da amikoj vi havas en la mondo?',
    'Ĉu viaj geamikoj fartas bone?',
    'Mia patro estas la unua filo de mia avo.',
    'Kiel viaj gepatroj fartas?',
    'Kie loĝas viaj fratoj?',
    'Kiom da gefratoj vi havas?',
    'Ĉu li iris al la lernejo?',
    'Ili ekiris en la frua mateno.',
    'Li kriis laŭte kun ĝojo.',
    'Ŝi ekkriis pro neatendita atako.',
    'La oro hele brilas.',
    'La stelo ekbrilas sur la ĉielo.',
    'Ĉu li venis de la najbara vilaĝo?',
    'Ĉu via amiko revenis malfrue?',
    'Ĉu vi memoras vian malnovan amikon?',
    'Li rememoris sian belan memoron.',
    'Mia patro donis la monon al mi.',
    'Ĉu vi redonis la libron al ŝi?',
    'Ĉu li donis la libron al vi?',
    'Ŝi disdonis la panon al ili.',
    'La rozoj disfloras en la ĝardeno.',
    'La ŝtoneto falis de la ŝtonego.',
    'La ponto disfalis abrupte.',
    'Kvankam (ŝi estas) riĉa, tamen ŝi vestas sin tre modeste.',
    'Ĉu li estas la prezidanto de nia klubo?',
    'Li estas la eksprezidanto de nia societo.',
    'Ĉu la vestaĵo estas lasta moda?',
    'Li vestis sin en la eksmoda vestaĵo.',
    'Li estas mia sincera edzo.',
    'Ĉu li estas via eksedzo?',
    'Ĉu vi komprenas miajn vortojn?',
    'Li miskomprenis mian sugeston.',
    'Ĉu via patro laboras en Seulo?',
    'Kie via prapatro loĝis antaŭ cent jaroj?',
    'Kun kiu via avo loĝas en la hejmloko?',
    'Ĉu lia praavo vivas feliĉe?',
    'Ĉu li estas saĝa homo?',
    'Kiel la prahomo faris fajron?',
    'Ĉu li estas kapabla prezidento?',
    'Nia vicprezidento estas tre honesta persono.',
    'Ĉu li estas nova ministro?',
    'Kia estas eksa vicministro?',
    'Ĉu li estas kuraĝa knabo?',
    'La knabino estas mia dua filino.',
    'Ĉu via kato estas aminda?',
    'La katinoj dormas sub la lito.',
    'Biblio estas la instruo de Jesuo.',
    'Kiel fartas via instruisto?',
    'La paco estas espero de la homaro.',
    'Oni vokas nin pacistoj.',
    'Mia familio konsistas el kvin personoj.',
    'Ĉiuj familianoj estas sanaj.',
    'Nia klubo havis kunsidon hieraŭ.',
    'Ĉu ŝi estas la klubano de Zamenhofa klubo?',
    'Ĉu via frato estas pli juna ol mi?',
    'La junulo devas havi ambicion.',
    'Ĉu la malsanulo iris al la malsanulejo?',
    'Hodiaŭ matene mi trinkis kafon.',
    'Ni renkontiĝos je la sesa horo ĉe kafejo.',
    'Mi skribas leteron al miaj amikoj en la mondo per reta poŝto.',
    'La skribilo estas necesa por skribi leteron.',
    'Ŝi tondas ŝiajn longajn harojn.',
    'Ĉu li tondas la branĉojn de la arbo per tondilo?',
    'Ĉu li havas sufiĉe da mono?',
    'Mia monujo estas malnova.',
    'Ĉu la kandelo estas en la tirkesto?',
    'Li metas la kandelon sur la kandelingon.',
    'Ŝia vesto estas eleganta kaj hela.',
    'Li portas vestaĉon kvazaŭ almozulo.',
    'Ĉu la domo de via amiko estas du etaĝa?',
    'Kiu loĝas en la domaĉo?',
    'Ĉu vi povas paroli en hispana lingvo?',
    'La parolado de la profesoro estis impresa.',
    'Ĉu la bebo dormas profunde?',
    'Li dormadas dolĉe kaj trankvile.',
    'Li manĝas manĝaĵon bonguste en la manĝejo.',
    'Ĉu la manĝaĵo estas akra?',
    'La diraĵo de la patro estas severa.',
    'Mi pakas mian sakon por vojaĝo.',
    'Ŝia pakaĵo estas peza kaj granda.',
    'Mi plantis la arbon hieraŭ.',
    'Tra la arbaro multaj homoj trapasis.',
    'Ĉu li estas sincera kaj homa homo?',
    'La paco estas bela sonĝo de la homaro',
    'Kial vi volas gajni monon?',
    'En mia poŝo estas nur monero.',
    'Ĉu tio estas via domo?',
    'La domego de mia amiko estas granda.',
    'Hodiaŭa vetero estas varmega.',
    'Li vivas ĉiam gaje kaj ĝoje kun rido.',
    'Ŝi etas rideton al mi.',
    'Kiam via Esperanto-amiko venos el Ĉinio?',
    'Nia amikeco daŭros eterne.',
    'Ĉu la bovo de via onklo laboras diligente?',
    'La bovido estas ido de la bovo.',
    'Li estas nia bona reĝo.',
    'Nia reĝido estas ĉarma kaj danda.',
    'Mia filo dormas en sia lito.',
    'Ĉu ŝi estas babilema virino?',
    'Ĉu vi ŝatas legi originalan novelon skribita en Esperanto?',
    'La novelo de la verkisto estis leginda por mi.',
    'Li manĝas la bongustan pomon.',
    'La pano, kiu estas farita de panjo, estas manĝinda.',
    'Li legas la libron pri Esperanto-movado.',
    'Ĉu la biografio pri Zamenhof estas legenda libro?',
    'Mi volas manĝi kun miaj familianoj.',
    'Ĉu ĝi estas manĝebla pano?',
    'Mia patro estas ĵurnalisto de la gazeto-kompanio.',
    'Kiu knabino vokas sian paĉjon?',
    'Ĉu vi komprenas la koron de via patrino?',
    'Mia panjo estas komprenema.',
    'Mi havas tri gefratojn.',
    'La triono de la kongresanoj estas azianoj.',
    'Du manoj faras ĉion, sed unu nenion.',
    'Duope ili ĵetis sin sur min.',
    'La gusto de la pano estas dolĉa.',
    'Bonvolu, gustumi la manĝa on.',
    'Li brakumis sian filinon varme.',
    'Mi plenumis mian mision sukcese.',
    'Mi malvarmumis hieraŭ nokte.',
    'Ĉu vi retumas ĉiutage kun viaj amikoj?',
    'Ni cerbumu por solvi la problemon.',
    'Proksimume, cent homoj aŭskultis lian prelegon.',
    'Ĉu ŝi povas fari bongustan kukon?',
    'Esperantisto ne fariĝas, sed naskiĝas',
    'Mia patrino naskis min en Seulo.',
    'Mi naskiĝis en la bela urbeto.',
    'En kiu urbo vi naskiĝis?',
    'Mi sidas sur la seĝo.',
    'Li sidigis min sur la seĝo.',
    'Ĉu la pejzaĝo de la monto estas bela?',
    'Ŝi beligas la ĉambron.',
    'Ĉu ŝi havas viglan karakteron?',
    'Printempo vigligas ĉian viva on en la mondo.',
    'Mi rigardas belan pejzaĝon.',
    'Du horojn, mi ludis tenison.',
    'La 2-an de Januaro mi renkontis lin.',
    'Mi paŝas en la ĉambro.',
    'Mi paŝas en la ĉambron.',
    'Mi transformiĝis en birdon.',
    'Kien vi iros?',
    'Mi iros hejmen.',
    'Saluton, Instruisto.',
    'Bonan matenon!',
    'Bonan tagon!',
    'Bonan vesperon!',
    'Mi tre ĝojas vidi vin.',
    'Mi tre ĝojas konatiĝi kun vi.',
    'Mia nomo estas Hong Gildong, kiu eklernis Esperanton antaŭ unu jaro.',
    'Mi loĝas en Seulo.',
    'Mi estas ankoraŭ komencanto.',
    'Mia profesio estas instruisto.',
    'Dankon, Sinjoro. Do, ĝis revido.',
    'Pli malrapide, mi petas.',
    'Pri kio vi demandis min?',
    'Pardonon, Sinjoro.',
    'Momenton.',
    'Ĉu vere?',
    'Ne gravas.',
    'Kiel diri ...? Kion diri...?',
    'Iom poste.',
    'Ĝis revido.',
    'Ĝis baldaŭ.',
    'Ĝis poste.',
    'Ĉu bone?',
    'Al kiu vi diris?',
    'Laŭ via volo.',
    'Laŭ via plaĉo.',
    'Kompreneble.',
    'Kio estas via profesio(okupo, laboro)?',
    'Bonvolu ripeti vian nomon.',
    'Hodiaŭa vetero estas tre agrabla.',
    'Kia estas hodiaŭa vetero?',
    'Nun pluvas en Seulo.',
    'Laŭ la veterprognozo,',
    'Nuna temperaturo estas tridek gradoj.',
    'Kiujn urbojn vi volas viziti morgaŭ?',
    'Kian impreson vi havas pri Koreio?',
    'Kiun vi volas renkonti en Seulo?',
    'Ĉu Koreio plaĉas al vi?',
    'Kiam vi revizitos Koreion?',
    'Kio estas via nomo?',
    'Mia nomo estas HONG Gildong.',
    'Mia familia nomo estas HONG, kaj persona nomo estas Gildong.',
    'Mi prezentas min.',
    'De kiu lando vi venis?',
    'Mi venis de Koreio, de Seulo.',
    'Jen estas mia nomkarto.',
    'Mi esperas, ke ni fariĝos bonaj amikoj.',
    'Dum via restado en Koreio, bonvole havu agrablan tempon.',
    'Kiam vi foriros?',
    'Kian laboron vi havas?',
    'Dankon pro via afableco.',
    'Estas mia plezuro.',
    'Jen estas menuo.',
    'Ĉu ni mendu?',
    'Kian manĝaĵon vi volas manĝi?',
    'Kia estas la gusto de la manĝaĵo?',
    'Ĉu mi rajtas fumi ĉi tie?',
    'Akvon mi petas.',
    'Mi volas manĝi glaciaĵon.',
    'Kian trinkaĵon vi volas?',
    'Ĉu vi prenos deserton?',
    'Kiamaniere oni manĝas ĉi tiun manĝaĵon?',
    'Mi regalos vin hodiaŭ.',
    'Duonon mi pagu.',
    'Ĝi estis bongusta!',
    'Kie estas bushaltejo?',
    'Kie mi povas preni tiun buson?',
    'Je kiu horo tiu buso startos?',
    'Je kiu horo vi revenos?',
    'Ĉu la buso iras al Seul-stacidomo?',
    'En kiu loko mi devas elbusiĝi?',
    'Ĉu vi povus rekomendi por mi vizitindan lokon?',
    'Kiom da minutoj ni bezonas de ĉi tie ĝis la muzeo per taksio?',
    'Kie estas taksio-haltejo?',
    'Turnu vin en la sekvanta angulo.',
    'Kie estas metroo-stacio?',
    'Vi prenu la duan linion.',
    'Kie mi ŝanĝu trajnon?',
    'Mi lasis sakon en la trajno.',
    'Ĉu eblas ricevi informilon?',
    'Bonvolu doni al mi turisman mapon?',
    'Kiu loko estas la plej vidinda?',
    'Kiamaniere mi atingu la lokon?',
    'Ĉu eblas iri piede ĝis tiu loko?',
    'Estas rekomendinde uzi taksion.',
    'Kiam la prezento finiĝos?',
    'Ĉu oni rajtas foti en la halo?',
    'Ĉu la biletoj estas elĉerpitaj?',
    'Kie mi nun estas?',
    'Ĉu vi bonvolus desegni la mapon?',
    'Ĉu vi bonvolus ekspliki por mi la vojon al Hotelo "Sejong"?',
    'Kie estas ĉiovendejo (magazeno)?',
    'Je kiu horo oni malfermas la pordon?',
    'Je kiu horo oni fermas la pordon?',
    'Ĉu tiu ĉi estas plej moda varo?',
    'Ĝi kostas tridek mil ŭonojn.',
    'Ĝi kostas tro multekosta.',
    'Ĉu vi povas doni al mi rabaton?',
    'Ĉu Petro estas hejme?',
    'Ĉu mi povus paroli kun Petro?',
    'Li ne estas hejme.',
    'Ĉu vi volas doni mesaĝon de vi?',
    'Mi petas vian telefonnumeron.',
    'Ĉu vi amas Esperanton?',
    'Ĉu viaj familianoj fartas bone?',
    'Ĉu vi povas paroli korean lingvon?',
    'Ĉu vi havas planon viziti koreion?',
    'Kiu estas via amika amiko en Koreio?',
    'Kia estas hodiaŭa vetero en via urbo?',
    'Kies verkaĵo estas impresa por vi?',
    'Kiu urbo estas vizitinda en via lando?',
    'Kie loĝas viaj gepatroj?',
    'Kien vi iros post via nuna laboro?',
    'Kiel vi lernis Esperanton?',
    'Kiam vi vizitos Koreion?',
];