VZ_course = [
    'Saluton!',
    'Mia nomo estas Zam.',
    'Mi ŝatas vojaĝi.',
    'Foje mi vojaĝas per trajno aŭ buso.',
    'Ofte mi flugas per aviadilo.',
    'Kaj nun mi vojaĝos kun vi!',
    'Apud la urbo Kairo, en la lando Egiptio, estas piramido.',
    'Fakte, ne estas nur unu piramido.',
    'Estas pluraj belaj piramidoj apud Kairo.',
    'Unu piramido nomiĝas Keopso.',
    'Krom la piramidoj estas alia interesa afero, la Sfinkso.',
    'En Novjorko estas la ĉefa sidejo de Unuiĝintaj Nacioj (UN).',
    'UN estas tre interesa organizo, mi pensas.',
    'Bedaŭrinde, multaj landoj ne bone kunlaboras kun UN hodiaŭ.',
    'Sed la ideoj malantaŭ UN estas vere bonaj.',
    'Eble iam UN pensos ke Esperanto estas bona ideo...',
    'Ne longe for de Pekino estas la ĉina muro.',
    'La ĉina muro estis farita antaŭ ĉirkaŭ 1800 (mil okcent) jaroj.',
    'La ĉinoj faris ĝin por protekti sin kontraŭ militemaj mongoloj.',
    'Mi aŭdis ke la ĉina muro estas la sola homfarita afero kiu videblas de la luno.',
    'Morgaŭ mi vojaĝos al la luno kaj kontrolos tion...',
    'En Stokholmo ĉiu-jare okazas disdonado de la Nobelpremio.',
    'La premion ricevas homoj kiuj grave kontribuis al la bono de la homaro.',
    'La kampoj de la premio estas certe tre gravaj.',
    'Ili estas: fiziko, kemio, medicino, literaturo kaj paco.',
    'La pacpremidonado ne okazas en Stokholmo sed aliloke (en Oslo, Norvegio).',
    'Velingtono estas la plej suda ĉefurbo el ĉiuj ĉefurboj.',
    'La urbo kuŝas ĉe maro, nome la Pacifika oceano.',
    'La Pacifika oceano estas la plej granda maro de la mondo.',
    'La aliaj oceanoj estas la Atlantika, la Barata kaj la Arkta.',
    'La Atlantika estas pli granda ol la Barata kiu estas pli granda ol la Arkta.',
    'Rio-de-Ĵanejro estas belega urbo.',
    'Unu-foje jare okazas grandega karnavalo tie.',
    'Tiam multege da homoj venadas al la urbo.',
    'Ili dancadas dum kvar tagoj kaj noktoj.',
    'Apud la urbo estas longega strando, pli ol 4 km longa.',
    'Tie oni povas kuŝadi, naĝadi kaj ĝuadi la vivon.',
    'En Bruselo laboras multaj politikistoj.',
    'Tie estas ankaŭ relative multe da ĵurnalistoj.',
    'Kial? Ĉar en Bruselo estas parlamentejo de la Eŭropa Unio.',
    'Ankaŭ la komisiono de EU havas sian ĉefan oficejon kun oficistoj tie.',
    'Kiom da tradukistoj kaj interpretistoj estas en Bruselo?',
    'Laŭ pluraj esperantistoj, tro...',
    'Jerusalemo estas sankta urbo por judoj, kristanoj kaj islamanoj.',
    'Do, aparte por anoj de tiuj religioj la urbo estas tre vizitinda.',
    'Vidindaj aferoj en la urbo estas ekzemple la plendomuro, la moskeo "el Aksa" kaj la tombopreĝejo.',
    'Bedaŭrinde, Jerusalemo ne ĉiam estas sekura por la urbanoj.',
    'En Parizo troviĝas alta konstruaĵo kiu nomiĝas la Eiffel-turo.',
    'La turo konstruiĝis en 1880-aj jaroj, laŭ la ideo de Gustave Eiffel.',
    'Laŭ kelkaj, la konstruaĵ-ideo estis granda stultaĵo.',
    'Sed la turo fariĝis mondfama kaj hodiaŭ ĝi estas tre populara vidindaĵo.',
    'Alia famaĵo en Parizo estas la Triumfa arko.',
    'En Lhasao estas la eksloĝejo de Dalai-lamao.',
    'En 1959 Dalai-lamao devis forlasi Lhasaon kaj Tibeton pro politikaj malfacilaĵoj.',
    'Sed li esperas povi reveni al Lhasao iam.',
    'Estas pli bone esperi ol ne esperi. (Dalai-lamao)',
    'Dalai-lamao kredas je reenkarniĝo kaj je amo al ĉiuj.',
    'Por praktiki toleremon, onia malamiko estas la plej bona instruisto. (Dalai-lamao)',
    'Mi ofte gajnas monon kiam mi estas en Las-vegaso.',
    'Sed amikino de mi, ŝi preskaŭ ĉiam malgajnas monon ĉi tie.',
    'Ŝi havas koramikon kaj li kutime malgajnas eĉ pli da mono ol ŝi!',
    'Sed ili ambaŭ estas tre riĉaj, do por ili ne tiom gravas.',
    'Tamen ni ĉiam bone amuziĝas en Las-vegaso.',
    'Mi esperas ke ankaŭ vi ŝatos la urbon, ĝi atendas vian monon!',
    'Kaburbo havas diversan popolon.',
    'Hodiaŭ la diversaj grupoj havas bonan rilaton inter si.',
    'Sed antaŭ kelkdek jaroj ne ĉiuj grupoj havis samajn rajtojn.',
    'En 1948 blankuloj enkondukis apartismon.',
    'Nelson Mandela kaj aliaj provis kontraŭlabori la apartismon.',
    'Pro tio la tiama registaro tenis ilin en malliberejo dum multaj jaroj.',
    'Feliĉe ĉio pliboniĝis kaj en 1994 Mandela fariĝis prezidento.',
    'En Meksikurbo loĝas mia familio grandparte.',
    'Miaj gefratoj kaj iliaj infanoj ĉiam pretas gastigi min.',
    'Ankaŭ la fratino de mi kaj ŝia edzo kaj lia frato parolas Esperanton.',
    'La 14-an de februaro estas festotago en Meksiko. Ĝia temo estas "amo kaj amikeco".',
    'Estas bonega tago por renkonti sian familion.',
    'Salutojn kaj bondezirojn al via familio!',
    'En St-Peterburgo ni vizitu mian bonan amikon Slavik.',
    'Lia filozofio kaj frapfrazo estas: "Esperu ĉiam!"',
    'Se mi loĝus en Rusio ankaŭ mi havus similan frapfrazon.',
    'Pardonu min! Mi nur ŝercis. Eble bonus se mi estus pli atenta pri miaj ŝercoj.',
    'Ĉiukaze, mia frapfrazo estas: "Ridetu kaj lernu!"',
    'Estus bone se vi farus ĝuste tion, ĉar tiel oni lernas lingvon pli rapide.',
    'La nomo Kusko en la keĉua signifas "umbiliko de la mondo".',
    'La keĉua estas la lingvo de la inkaoj.',
    'La imperio Inkaa ekzistis ekde 1200 (mil ducent) ĝis 1533 (mil kvincent tridek tri).',
    'Nuntempe la plejparto de la loĝantoj de Kusko estas indianoj, posteuloj de la Inkaa imperio.',
    'La alteco de Kuzco estas ĉirkaŭ 3 400 metroj.',
    'Proksime de Kusko troviĝas ankaŭ alia fama urbo de la inkaoj, Machu Pikĉu.',
    'Irkuco estas grava centro en Siberio.',
    'Vi eble demandas vin: "Kio estas Siberio?"',
    'Siberio estas vastega parto de la azia teritorio de Rusio.',
    'Kiel oni povas atingi Irkuckon?',
    'Oni povas atingi ĝin per la transsiberia fervojo. Tiel multaj vojaĝas.',
    'Zam ekvidas ĉarman rusinon kaj diras: "Saluton! Kio estas via nomo? Kiel vi fartas?"',
    'Kioto estas konata pro siaj bonaj manĝaĵoj.',
    'Kia estas la manĝaĵo en Kioto? Ĝi estas freŝa kaj bongusta!',
    'Mi plej ŝatas Suŝion, aŭ alivorte, japanajn rizvolvaĵojn.',
    'Kiom da Suŝi-pecoj mi povas manĝi?',
    'Tiom da pecoj kiom estas!',
    'Kiom kontenta vi estas pri tia respondo?',
    'Kia demando, tia respondo. kiel diras la proverbo...',
    'Nuko estas la plej granda urbo sur la plej granda insulo de la mondo, Gronlando.',
    'Ĉu vi scias kies estas Gronlando?',
    'Ĝi fakte estas parto de la dana regno.',
    'Tamen ekde la jaro 1979 Gronlando estas politike memstara.',
    'Ĉu Gronlando apartenas al Eŭropo? Ne, almenaŭ ne el geografia vidpunkto.',
    'Ĉu la glaciursoj zorgas pri kies estas Gronlando? Kredeble ne.',
    'Kiam fondiĝis Samarkando?',
    'Jam antaŭ 5 mil jaroj - ĝi estas unu el la plej malnovaj centroj de la monda civilizo.',
    'Islamo venis al Samarkando en la oka jarcento, kiam araboj ekloĝis en la urbo.',
    'Kial Samarkando estis grava dum tiom da jaroj?',
    'Ĉar tra ĝi iris la Granda Silka Vojo inter Eŭropo kaj Ĉinio.',
    'Kaj kial Samarkando estas aparte interesa por esperantistoj?',
    'Ĉar en ĝi esperantistoj fondis la Internacian Muzeon de Paco kaj Solidaro.',
    'Kie ni estas? Vi jam scias, sur la pinto de Kilimanĝaro.',
    'Kiu povas atingi la pinton, sur kiu ni nun estas?',
    'Tiuj kiuj estas bone trejnitaj kaj ŝatas migregi.',
    'Fakte, ni nun staras sur loko kie antaŭe estis aktiva vulkano.',
    'Sed hodiaŭ Kilimanĝaro estas tute trankvila kaj afabla monto.',
    'Kiu agas afable, vivas agrable kiel diras la proverbo.',
    'Kaj mi deziras al vi afablan kaj agrablan pluvojaĝon, kien ajn vi iros!',
];
